'use client';
import React from 'react';
import { BaseEdge, EdgeProps, getSmoothStepPath } from '@xyflow/react';

const BUMP_R    = 7;   // radius of bridge bumps at crossings
const CLEARANCE = 28;  // minimum distance from node border before turning
const CORNER_R  = 14;  // radius of rounded corners

/** Returns true if cx is strictly between a and b (±margin). */
function isBetween(cx: number, a: number, b: number, margin = 20): boolean {
  const lo = Math.min(a, b) + margin;
  const hi = Math.max(a, b) - margin;
  return cx >= lo && cx <= hi;
}

/** 
 * Parses an SVG path generated by getSmoothStepPath and injects arc bumps 
 * into any horizontal segments that intersect the known vertical crossings.
 */
function injectBumps(path: string, crossings: number[], br: number): string {
  if (!crossings || crossings.length === 0) return path;

  // Split path into individual SVG commands
  const parts = path.split(/(?=[MLQZ])/i);
  let result = '';
  let cx = 0;
  let cy = 0;

  for (const part of parts) {
    if (!part.trim()) continue;
    const type = part[0].toUpperCase();
    const coordsStr = part.slice(1).trim().replace(/,/g, ' ');
    const coords = coordsStr.split(/\s+/).filter(Boolean).map(Number);

    if (type === 'M') {
      cx = coords[0];
      cy = coords[1];
      result += part;
    } else if (type === 'L') {
      const tx = coords[0];
      const ty = coords[1];
      
      // If the line is perfectly horizontal
      if (Math.abs(ty - cy) < 1) {
        const goRight = tx > cx;
        // Find crossings that actually fall inside this horizontal segment
        const sorted = crossings
          .filter(x => isBetween(x, cx, tx, br + 2))
          .sort((a, b) => goRight ? a - b : b - a);
        
        let d = '';
        const sweep = goRight ? 1 : 0;
        for (const bumpX of sorted) {
          d += ` L ${bumpX - br} ${cy} A ${br} ${br} 0 0 ${sweep} ${bumpX + br} ${cy}`;
        }
        d += ` L ${tx} ${ty}`;
        result += d;
      } else {
        result += part;
      }
      cx = tx;
      cy = ty;
    } else if (type === 'Q') {
      // Q commands have 4 coordinates: controlX, controlY, endX, endY
      cx = coords[2];
      cy = coords[3];
      result += part;
    } else {
      result += part;
    }
  }

  return result;
}

// ─── SmartEdge component ────────────────────────────────────────────────────
export default function SmartEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style = {},
  markerEnd,
  data,
}: EdgeProps) {
  const crossings: number[] = (data as any)?.crossings ?? [];

  // 1. Generate a perfect orthogonal path using XY Flow's robust router
  // This automatically respects sourcePosition/targetPosition and guarantees clearance (offset)
  const [basePath] = getSmoothStepPath({
    sourceX, sourceY, sourcePosition,
    targetX, targetY, targetPosition,
    borderRadius: CORNER_R,
    offset: CLEARANCE,
  });

  // 2. Inject arc bumps wherever the path's horizontal segments cross a vertical line
  const path = injectBumps(basePath, crossings, BUMP_R);

  return (
    <>
      {/* Fat invisible hit area for easier click/touch */}
      <BaseEdge id={id + '_hit'} path={path} style={{ stroke: 'transparent', strokeWidth: 18 }} />
      {/* Visible styled path */}
      <BaseEdge id={id} path={path} style={style} markerEnd={markerEnd} />
    </>
  );
}
