name = "campuslink"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Carpeta de salida limpia para Cloudflare Pages
pages_build_output_dir = ".cloudflare-out"

# Variables de entorno (configurar también en Cloudflare Dashboard)
[vars]
NODE_ENV = "production"
