
CREATE TEMP TABLE temp_prof_updates (
  nombre text,
  especialidad text,
  otros_cursos text
);
INSERT INTO temp_prof_updates (nombre, especialidad, otros_cursos) VALUES
('PARDO GRAU, Cecilia Maria Luisa', 'Antiguo Perú, Arqueología, Museos y Nuevas Tecnologías', 'Arte y diseño prehispánico. Naturaleza y legado, Introducción a las Humanidades Digitales'),
('DEL MASTRO PUCCIO, Cesare Anibal', 'Antropología Filosófica', 'Filosofía, Introducción a la Política, Filosofia y Economía'),
('ESPINOSA WINDER, Francisco', 'Comunicación Digital', 'Lectura Crítica de la Prensa Digital y en las Redes Sociales'),
('PIEDRA VALDEZ, Jose Leopoldo', 'Dios, Existencia Humana y Sociedad', 'Ética'),
('VARGAS DELLA CASA, Rosa Elvira', 'Ética', NULL),
('QUIROZ MEZA, Danitza Dejanira', 'Ética', 'Filosofía'),
('PONCE BOGINO, Hector Alberto', 'Ética', NULL),
('EGOAVIL RIOS, Jean Christian', 'Ética', NULL),
('HINOSTROZA RIVERA, Dino Arturo', 'Ética', NULL),
('IVANOFF SABOGAL, Christian', 'Ética', NULL),
('ARANA ALENCASTRE, Jean Luis', 'Ética', NULL),
('VILLARAN CONTAVALLI, ALONSO MANUEL', 'Ética', NULL),
('DEXTRE UZATEGUI, Sergio Guillermo', 'Ética', 'Filosofía'),
('MORENO GONZALEZ, Rafael', 'Ética', 'Filosofía'),
('CARRIÓN CARAVEDO, Úrsula', 'Filosofía', 'Filosofia Política, Lenguaje II'),
('LASTRES DAMMERT, Pamela Maria', 'Filosofía', NULL),
('IBAÑEZ BLANCAS, Franklin Ernesto', 'Filosofía', NULL),
('ASTUDILLO TORRES, Deyvi Harold', 'Filosofía', NULL),
('FONSECA ARIZA, Juan Adoniran', 'Historia Crítica del Perú', 'Religiones, Culturas y Economía'),
('INJOQUE RONCEROS, Freddy Miguel', 'Historia Crítica del Perú', 'Pensamiento Social Contemporáneo, Análisis de Datos Geográficos'),
('LIZARME VILLCAS, Nashely Yuvitza', 'Historia Crítica del Perú', NULL),
('MONSALVE ZANATTI, Martin Alberto', 'Historia Económica del Perú', 'Historia y Filosofía de la Ciencia'),
('CAMACHO GAVIDIA, Abel Fernando', 'Historia Económica del Perú', 'Historia Económica y Empresarial'),
('CASAS TRAGODARA, Carlos Augusto', 'Historia Económica del Perú', 'Econometría II, Macroeconomía de Corto Plazo, Macroeconomía III'),
('RODRIGUEZ SATIZABAL, Beatriz Helena', 'Historia Económica y Empresarial', NULL),
('CARRASCO WESTON, Jose Manuel', 'Historia Económica y Empresarial', NULL),
('BARRETO VELAZQUEZ, Norberto', 'Historia Económica y Empresarial', NULL),
('CABREJOS PORTOCARRERO, Jose Ignacio', 'Historia Económica y Empresarial', NULL),
('PEREZ MARTINEZ, Angel Ruben', 'Historia y Filosofía de la Ciencia', NULL),
('GUADALUPE MENDIZABAL, Cesar Augusto', 'Historia y Filosofía de la Ciencia', NULL),
('BARRON AYLLON, Manuel Fernando', 'Introducción a la Política, Filosofia y Economía', 'Econometría I, Microeconomía II'),
('PEREZ , Leda Margarita', 'Introducción a la Política, Filosofia y Economía', NULL),
('NASSI PERIC, Bruno Fernando', 'Lenguaje I', 'Lenguaje II'),
('LANDA ROJAS, Luis Enrique', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('QUIROZ VELA, Juan Enrique', 'Lenguaje I', 'Nivelación en Lenguaje'),
('MORIMOTO SONE, Maria Lourdes', 'Lenguaje I', NULL),
('MONTAUBAN DEL SOLAR, Michele Marie', 'Lenguaje I', NULL),
('GAUGER QUIROZ, Juan Manuel', 'Lenguaje I', 'Nivelación en Lenguaje'),
('PINASCO ESPINOSA, Sandra Gabriella', 'Lenguaje I', NULL),
('HELGUERO MORALES, Lorenzo Pedro', 'Lenguaje I', 'Lenguaje II'),
('MADALENGOITIA BARUA, Maria Gracia', 'Lenguaje I', 'Nivelación en Lenguaje'),
('PEREZ DEL SOLAR TOLA, Pedro Carlos Hilarion', 'Lenguaje I', 'Lenguaje II'),
('CALDERÓN BAIOCCHI, Juan Humberto', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('MERINO SILICANI DE ALVAREZ, Rosanna Maria', 'Lenguaje I', 'Nivelación en Lenguaje'),
('CARRILLO PASTOR, Giuliana Maria', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('GUTIERREZ MEZA, José Elías', 'Lenguaje I', NULL),
('GUICH RODRIGUEZ, Jose Abelardo', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('ZAPATA FAJARDO, Jaime Israel', 'Lenguaje I', 'Lenguaje II'),
('MORILLO SOTOMAYOR, Alex', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('HUATUCO POMALAZA, Rocio Milagros', 'Lenguaje II', 'Nivelación en Lenguaje'),
('SALCEDO REYES, Ana Lucia', 'Lenguaje II', NULL),
('FERRUCCI MONTOYA, Gabriela Ida', 'Lenguaje II', NULL),
('WIESSE REBAGLIATI, Jorge Raul', 'Literatura', NULL),
('GATTI MURRIEL, Carlos Antonio', 'Literatura Universal', NULL),
('VARGAS VILCA, Mariano Daniel', 'Nivelación en Lenguaje', NULL),
('ARMAS ASIN, Fernando Alberto', 'Religiones, Culturas y Economía', NULL),
('ROMERO PINTO, Ezequiel Eduardo', 'Religiones, Culturas y Economía', NULL),
('FLORES PAZ, Rafael Antonio', 'Religiones, Culturas y Economía', NULL),
('ATO DEL AVELLANAL CARRERA, Manuel Antonio', 'Religiones, Culturas y Economía', NULL),
('ARIAS CUBA, Ybeth Merly', 'Religiones, Culturas y Economía', NULL),
('CARO JAHNCKE, Andres Javier', 'Análisis Económico de la Competencia', NULL),
('ALVAREZ RODRICH, Augusto Anibal', 'Análisis Político Relevante para la Perspectiva Económica', NULL),
('GARCIA RAMOS, Yboon Victoria', 'Análisis Real y Convexo', 'Matemáticas IV'),
('QUISPE ROJAS, Alexander Wilder', 'Data Science con Python', 'Inferencia Causal y Machine Learning'),
('PRIALE UGAS, Miguel Enrique', 'Diseño y Evaluación Social de Proyectos', 'Economía General I'),
('BASURTO PRECIADO, Maria Pia', 'Econometría Aplicada', 'Econometría II'),
('CASTRO CARLIN, Juan Francisco', 'Econometría I', NULL),
('LAVADO PADILLA, Pablo Augusto', 'Econometría I', 'Econometría II'),
('GALARZA CONTRERAS, Elsa Patricia', 'Economía Ambiental Aplicada a las Políticas Públicas en el Perú', 'Microeconomía II'),
('GALARZA ARELLANO, Francisco Bruno', 'Economía Experimental', 'Microeconomía II'),
('LA SERNA STUDZINSKI, Karlos', 'Economía General I', NULL),
('PARODI TRECE, Carlos Alfredo Justo', 'Economía General I', 'Economía Peruana'),
('GÓMEZ GAMARRA DE ZEA, ZOILA DEL ROSARIO', 'Economía General I', NULL),
('MOLINA CAMPODONICO, Oswaldo', 'Economía General I', NULL),
('AGUIRRE MONTOYA, Julio Cesar', 'Economía General I', 'Organización Industrial'),
('HERNANDEZ RUBIÑOS, Mario German', 'Economía General I', NULL),
('PEREZ MALCA, Patricia Estela', 'Economía General I', NULL),
('MONTESINOS CORDOVA, Jorge Luis', 'Economía General I', 'Economía General II, Evaluación Privada de Proyectos'),
('PAREDES SALAZAR, Lizardo Emanuel', 'Economía General I', NULL),
('ARAGON PEÑALOZA, Gisella Silvana', 'Economía General I', NULL),
('FALEN ZEVALLOS, Luis Eduardo', 'Economía General I', 'Economía General II'),
('TALLEDO SANCHEZ, Jacqueline Isabel', 'Economía General I', NULL),
('RIVERA GALLEGOS, Gonzalo Javier', 'Economía General I', 'Microeconomía I'),
('HERAS RIVERA, Sissi Andrea', 'Economía General I', NULL),
('MUÑIZ CAHUANA, Graciela Rocio', 'Economía General I', NULL),
('LISBOA VASQUEZ, Claudia Paola', 'Economía General I', NULL),
('SEVERINO MUÑOZ, Renzo Cristhyan Enrique', 'Economía General I', NULL),
('SALINAS DEPAZ, Cesar Saturnino', 'Economía General II', NULL),
('FRANCO VALDIVIA, Eliana', 'Economía General II', 'Investigación Aplicada en Negocios Internacionales'),
('DIAZ GAZANI, Guillermo', 'Economía General II', NULL),
('SERVAN LOZANO, Sergio', 'Economía General II', NULL),
('VEGA DE LA CRUZ, Hugo Yamil', 'Economía General II', NULL),
('ROJAS RODRIGUEZ, CARMEN ROSA', 'Economía General II', NULL),
('GONZAGA MENA, Bruno Eduardo', 'Economía General II', NULL),
('URRUNAGA PASCO-FONT, Roberto Luis', 'Economía Pública', 'Macroeconomía I'),
('MUÑOZ BAZAN, Italo Juan Carlos', 'Economía y Estadística Aplicada al Derecho', NULL),
('ROMERO VEREAU, Daniel Alonso', 'Estadística Aplicada', NULL),
('SALINAS MORRIS, Juan Carlos', 'Estadística Aplicada', 'Análisis Financiero'),
('CHIRA BALLENA, Miguel Angel', 'Estadística Aplicada', NULL),
('TRUJILLO GALINDO, Renato Juan', 'Estadística Aplicada', NULL),
('MATEU BULLON, Pedro Fernando', 'Estadística I', 'Estadística II'),
('PEREZ SOTELO, Edisson Alonso', 'Estadística I', 'Matemáticas III, Nivelación en Matemáticas'),
('RUBIO DONET, Jorge Luis', 'Estadística I', 'Estadística II'),
('ANGELES OLIVERA, Julio Hugo', 'Estadística I', 'Estadística II'),
('SOTO RODRIGUEZ, Ivan Dennys', 'Estadística I', 'Estadística II'),
('LINDO HUERTAS, Elsa Maria', 'Estadística I', 'Estadística II'),
('TARAZONA VARGAS, Enver Gerald', 'Estadística I', 'Estadística II'),
('OSORIO MAURICIO, Lucila', 'Estadística I', NULL),
('CAYCHO HUAMANI, Jose Alberto', 'Estadística I', 'Análisis Multivariado para los Negocios, Investigación de Mercados Aplicada'),
('SILVESTRE VALER, Jim Roland', 'Estadística I', NULL),
('VALENCIA CHACON, Raphael Felix', 'Estadística I', NULL),
('FEBRES HUAMAN, Grimaldo Jose', 'Estadística I', NULL),
('SOTO RODRIGUEZ,', 'Estadística II', NULL),
('LI NING CHAMAN, Jorge Francisco', 'Evaluación Privada de Proyectos', NULL),
('KAMICHE ZEGARRA, Joanna Noelia', 'Gestión de los Recursos Naturales', NULL),
('MANRIQUE ZEDER, Liseth Cristina', 'Gestión de los Recursos Naturales', NULL),
('GUARDIA MUGURUZA, Alejandra', 'Green Growth Strategies for Peru and Latin America', NULL),
('TORRES GOMEZ, Javier Antonio', 'Historia del Pensamiento Económico', 'Macroeconomía I'),
('DEL HIERRO CARRILLO, Patricia', 'Historia del Pensamiento Económico', 'Sem. La IA y la Robótica: Ciclos Económicos, Impactos y Respuestas'),
('GONZALEZ VIGIL, Luis Fernando', 'Investigación Económica I', 'Investigación Económica II'),
('MORON PASTOR, Eduardo Andres', 'Macroeconomía I', NULL),
('CUSATO NOVELLI, Antonio', 'Macroeconomía I', NULL),
('ORTIZ SOSA, Marco Antonio', 'Macroeconomía II', NULL),
('PAWELCZAK , Jakub Mateusz', 'Macroeconomía II', NULL),
('CASTILLO AGUIRRE, Luis Eduardo', 'Macroeconomía II', NULL),
('PINZON GIRALDO, Alvaro Jose', 'Macroeconomía III', NULL),
('HERNANDEZ CALDERON, Joao Alejandro', 'Macroeconomía Internacional', NULL),
('MONTORO LLAMOSAS, Carlos Humberto', 'Macroeconomía Internacional', NULL),
('CHAVEZ SARMIENTO, Enrique Idael', 'Matemáticas I', 'Procesos Estocásticos'),
('OLANO CRUCES, Mario Fernando', 'Matemáticas I', NULL),
('FLORES SALINAS, JOSE ALBERTO', 'Matemáticas I', 'Matemáticas II, Matemáticas para los Negocios'),
('ESCUDERO ACERO, Phamela Stephany', 'Matemáticas I', 'Matemáticas para los Negocios, Nivelación en Matemáticas'),
('DAVILA QUESQUEN, Erick Nomberto', 'Matemáticas I', 'Matemáticas II'),
('PROLEON PATRICIO, DANIEL GIOVANNI', 'Matemáticas I', NULL),
('ESCALANTE HUAMANÍ, Sonia María', 'Matemáticas I', 'Matemáticas para los Negocios, Nivelación en Matemáticas'),
('GUARDALES VASQUEZ, Randdy Arturo', 'Matemáticas I', 'Nivelación en Matemáticas'),
('MOLINA TARAZONA, Lucy Smith', 'Matemáticas I', 'Matemáticas II, Nivelación en Matemáticas'),
('SINCHE CHOCCA, Nildo', 'Matemáticas I', 'Nivelación en Matemáticas'),
('ALCALDE SOSA, Jose Andres', 'Matemáticas I', 'Matemáticas III'),
('SALINAS ZAVALA, Christoper Jesus', 'Matemáticas I', 'Matemáticas II, Nivelación en Matemáticas'),
('ARREDONDO RUIZ, Manuel Jesus', 'Matemáticas I', 'Pensamiento Sistémico'),
('BUENO TANGOA, Orestes Martin', 'Matemáticas II', 'Matemáticas III'),
('CHULLUNCUY CENTENO, Andres Vicente', 'Matemáticas II', 'Nivelación en Matemáticas'),
('TORRES PEREZ, Elvis', 'Matemáticas II', NULL),
('COTRINA ASTO, John Edwin', 'Matemáticas III', 'Matemáticas IV'),
('WINKELRIED QUEZADA, Diego Martin', 'Matemáticas III', 'Investigación Financiera, Sem. Commodities & Volatility, Sem. de Proceso de Mercado'),
('VELASQUEZ CASTAÑON, Oswaldo Jose', 'Matemáticas III', 'Álgebra Líneal Aplicada, Programación Avanzada para la Ciencia de Datos'),
('MANTILLA GONZALES DE LA COTER, Eduardo Javier', 'Matemáticas IV', NULL),
('OSORIO UBALDO, Jaime', 'Matemáticas para los Negocios', 'Nivelación en Matemáticas'),
('CORTEZ VALDIVIA, Rafael Augusto', 'Microeconomía I', NULL),
('RHO , Haedong', 'Microeconomía I', NULL),
('CHAVEZ COTRADO, Jorge Francisco', 'Microeconomía I', 'Microeconomía II'),
('PORRAS MENDOZA, Linda Janet', 'Microeconomía I', 'Sem. Economía y Gestión de Programas Sociales'),
('BONIFAZ FERNANDEZ, Jose Luis', 'Microeconomía II', 'Organización Industrial'),
('CERNADES GOMEZ, Jesus', 'Nivelación en Matemáticas', NULL),
('VENEGAS PALACIOS, Edgard Kenny', 'Nivelación en Matemáticas', NULL),
('GONZALEZ IZQUIERDO, Jorge Domingo', 'Política Económica', NULL),
('ARMAS RIVAS, Adrian Alejandro', 'Política Económica', NULL),
('ARON SAID, Ana Sofia', 'Sem. de la Estrategia a la Implementación de Políticas Públicas', NULL),
('DIAZ GAMARRA, Jose Guillermo', 'Sem.Tópicos en Organización Industrial', NULL),
('ARAOZ FERNANDEZ, Mercedes Rosalba', 'Teoría del Comercio Internacional', NULL),
('ZEVALLOS URQUIETA, Hector Augusto', 'Teoría del Comercio Internacional', NULL),
('CANTA TERREROS, Michel Rodolfo', 'Teoría del Desarrollo Económico', NULL),
('MALDONADO ZAMBRANO, Stanislao Humberto', 'Tópicos de Evaluación de Impacto', NULL),
('BENITES SANCHEZ, Luis Enrique', 'Análisis Multivariado para los Negocios', 'Analítica de Datos para los Negocios'),
('DONGO ROMAN, Andie Bryan', 'Análisis Multivariado para los Negocios', NULL),
('GARCIA CESPEDES, Carlos Jeffer', 'Análisis Multivariado para los Negocios', NULL),
('PORRAS CERRON, Jaime Carlos', 'Análisis Multivariado para los Negocios', 'Fundamentos de Analítica'),
('CASTILLO ISISOLA, Frank Josue', 'Análisis Multivariado para los Negocios', NULL),
('VASQUEZ ORE, Marco Antonio', 'Analítica de Datos para los Negocios', 'Macros en Excel para No Programadores, Nivelación en Informática'),
('MAEHARA ALIAGA, Yoshitomi Eduardo', 'Analítica de Datos para los Negocios', 'Herramientas de Programación'),
('BUSTAMANTE BAUTISTA, Beatriz Esther', 'Analítica de Datos para los Negocios', 'Nivelación en Informática'),
('RAMOS PERALTA, Karim Mabel', 'Analítica de Datos para los Negocios', 'Nivelación en Informática'),
('REATEGUI SCHWARZ, Gerardo', 'Asset-Light Business Models', NULL),
('VILLACORTA HOLGUIN, Katherine Lilia', 'Business Agility', 'Design Thinking and Technological Innovation'),
('PERALTA MANSILLA, Norma Gisela', 'Business Agility', 'Emprendimiento e Innovación, Proyección Social'),
('FLORES CASTRO, Juan Alejandro', 'Creación de Valor y Toma de Decisiones', 'Diseño Organizacional y Estrategia, Gestión de la Innovación'),
('Díaz Rojas, Carlos Andres', 'Creación de Valor y Toma de Decisiones', 'Métodos Cuantitativos para la Gestión en las Organizaciones, Sistemas de Información y Análisis de Datos'),
('LAFOSSE QUINTANA, Wilfredo Jesus', 'Creación de Valor y Toma de Decisiones', 'Dirección Estratégica'),
('PAIVA ZARZAR, Roberto Alcides', 'Dirección Estratégica', NULL),
('PALACIOS MATOS, Maria Del Pilar Amelia', 'Dirección Estratégica', 'Gestion del Capital Humano, Liderazgo, Transformación Digital y Gestión del Cambio'),
('UEYONAHARA MATZUMOTO, Jorge Antonio', 'Diseño de Negocios Circulares y Desafío Climático', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas, Liderazgo, Sostenibilidad Empresarial y Modelos de Negocios Circulares'),
('REBAZA CARO, Nancy', 'Diseño Organizacional y Estrategia', 'Fundamentos de las Ciencias Empresariales, Gestión del Cambio y Transformación Cultural, Liderazgo'),
('ACUÑA SILLO, Elba Lourdes', 'Diseño Organizacional y Estrategia', 'Estrategia, Fundamentos de las Ciencias Empresariales'),
('JAYME MOSQUERA, Guadalupe Desiree', 'Diseño Organizacional y Estrategia', 'Fundamentos de las Ciencias Empresariales, Gestión de Personas, Gestión del Cambio y Transformación Cultural'),
('BUTRON PIPOLI, Giuliana Maria', 'Diseño Organizacional y Estrategia', NULL),
('GRANTHON URIARTE, Ronald Jefrie', 'Diseño Organizacional y Estrategia', 'Fundamentos de las Ciencias Empresariales, Liderazgo'),
('TRUJILLO SOSA, Jorge Enrique', 'Emprendimiento e Innovación', 'Fundamentos de las Ciencias Empresariales, Proyecto Empresarial'),
('SANCHEZ JUGO, Isabel', 'Emprendimiento e Innovación', 'Fundamentos de las Ciencias Empresariales, Comportamiento del Consumidor'),
('VILLANUEVA PEREZ, Humberto Jesus', 'Emprendimiento e Innovación', NULL),
('VILLEGAS VALLADARES, Shirley Rubi', 'Emprendimiento e Innovación', 'Proyecto Empresarial'),
('BELTRÁN PUERTA, Jorge', 'Emprendimiento e Innovación', NULL),
('RIVAS VELARDE, Andrea Carolina', 'Emprendimiento e Innovación', 'Marketing Estratégico'),
('RODRIGUEZ CORNEJO, Juan Carlos', 'Formación y Desarrollo del Talento', NULL),
('CORNEJO ALVAREZ DE ESQUIVES, Ana Lourdes', 'Fundamentos de las Ciencias Empresariales', 'Proyecto Empresarial'),
('WEINBERGER VILLARAN, Karen Edith', 'Fundamentos de las Ciencias Empresariales', NULL),
('DEL CASTILLO MORY, Elsa Catalina', 'Fundamentos de las Ciencias Empresariales', NULL),
('MANOSALVA MENDOZA, Maritza Elva Juana', 'Fundamentos de las Ciencias Empresariales', 'Gestión del Cambio y Transformación Cultural'),
('MEDINA WONG, Gwendolyne', 'Fundamentos de las Ciencias Empresariales', NULL),
('ANTICONA SUAREZ, Erick Olson', 'Gestión de la Cadena de Suministros', 'Gestión de Operaciones en las Organizaciones, Proyecto Empresarial, Logística Internacional, Tecnologías Aplicadas a la Distribución Física Internacional'),
('OLIVEIRA CAMBIASO, Daniel Alessandro', 'Gestión de la Cadena de Suministros', NULL),
('CHICHIZOLA FAJARDO, Cristina Elizabeth', 'Gestión de la Cadena de Suministros', 'Gestión de Operaciones en las Organizaciones, Métodos Cuantitativos para la Gestión en las Organizaciones'),
('PECASTAING , Nicolas', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas', NULL),
('PRIALE VALLE, Maria Angela', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas', NULL),
('TEJADA MATOS, Susana Rocío', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas', NULL),
('SARAVIA VERGARA, Enrique Andres', 'Gestión de Operaciones en las Organizaciones', 'Métodos Cuantitativos para la Gestión en las Organizaciones'),
('LARIOS FRANCIA, Rosa Patricia', 'Gestión de Operaciones en las Organizaciones', 'Gestión y Emprendimiento en la Industria Musical, Investigación Aplicada a los Negocios'),
('ESQUIVES GUERRA, Marcial Ruben', 'Gestión de Personas', 'Gestión del Cambio y Transformación Cultural, Liderazgo, Selección y Evaluación de Personal'),
('FUCHS ANGELES, Rosa Maria', 'Gestión de Personas', NULL),
('OTINIANO CARBONELL, Martin Carlos', 'Gestión de Personas', 'Gestión del Cambio y Transformación Cultural'),
('CAMPOS FERNANDEZ, Luis Enrique', 'Gestión de Riesgos según el PMI', NULL),
('BRAVO MONTEVERDE, Guido Humberto', 'Gestión del Cambio y Transformación Cultural', 'Liderazgo'),
('ESCRIBENS OLAECHEA, Mario Eduardo', 'Gestion del Capital Humano', 'Introducción a la Ingeniería, Tecnología y Negocios Digitales'),
('GOMEZ CHANGA, Sarita Julia', 'Gestión Estratégica de Organizaciones Deportivas', 'Liderazgo, Marketing Deportivo'),
('MOSCOSO ZAMBRANO, Renzo Mauricio', 'Gestión Estratégica de Organizaciones Deportivas', 'Marketing Deportivo'),
('Alpaca', 'Gestión y Emprendimiento en la Industria Musical', NULL),
('CHAVEZ CARRUITERO, Jimmy Rosendo', 'Innovación y Gestión en Negocios Digitales', 'Sistemas de Información y Análisis de Datos'),
('LINARES TORRES, Freddy', 'Innovación y Gestión en Negocios Digitales', 'Digital Product Design & Metrics, Neuromarketing'),
('GARCIA FRY, Andrea', 'Innovación y Gestión en Negocios Digitales', NULL),
('ESPINEL HUERTAS DEL PINO, Maria Pia', 'Innovación y Gestión en Negocios Digitales', NULL),
('CANO LANZA, Ana Maria', 'Investigación Aplicada a los Negocios', NULL),
('CHAVES CUZZI, Daniela Maria', 'Liderazgo', NULL),
('HERAUD GOICOCHEA, Sylvia', 'Liderazgo', NULL),
('Vivanco Loomer, Luis Miguel', 'Liderazgo', NULL),
('Vargas Soto, Veronica', 'Liderazgo', NULL),
('CASTRO SEGURA, Barbara', 'Liderazgo', NULL),
('SALVADOR , Elisa', 'Managing Innovation and Creativity - Negotiation for International Managers', NULL),
('DAVALOS CHACON, Jorge Elias', 'Métodos Cuantitativos para la Gestión en las Organizaciones', NULL),
('BRESCIANI CHAVEZ, Fernando Manuel', 'Métodos Cuantitativos para la Gestión en las Organizaciones', 'Fundamentos de Finanzas'),
('GALVEZ PAIBA, Blanca Eliana', 'Proyecto Empresarial', NULL),
('ARANDA IPINCE, Duilio Angel', 'Sistemas de Información y Análisis de Datos', 'Arquitectura del Sistema de Información, Nivelación en Informática, Power BI: Transforma y Visualiza Datos para Decisiones Informadas'),
('INFANTE CHAVEZ, Jorge Ricardo', 'Sistemas de Información y Análisis de Datos', 'Arquitectura del Sistema de Información, Excel Avanzado para la Gestión Empresarial, Nivelación en Informática'),
('CASAFRANCA ROSAS, Juan Carlos', 'Toma de Decisiones - Simulador: Blue Ocean Strategy', NULL),
('VALDIVIA CORRALES, Gustavo', 'Antropología', 'Antropología Económica'),
('CASTELLANOS DEL PORTAL, Themis Aidee', 'Antropología', NULL),
('Hidalgo Bonicelli, Alejandra Lucia', 'Antropología', 'Investigación Académica'),
('PAGAN SANCHEZ, Antonio Jose', 'China Contemporánea: Sociedad, Política y Relaciones Internacionales', 'Relaciones Internacionales'),
('PASTOR TORRES, Gustavo Ricardo', 'Ciencia Política', 'Investigación Académica, Pensamiento Social Contemporáneo'),
('VERGARA PANIAGUA, Alberto', 'Ciencia Política', NULL),
('BLYDAL , Carl Johan', 'Ciencia Política', NULL),
('LANEGRA QUISPE, Ivan Kriss', 'Ciencia Política', NULL),
('MARIUS VASQUEZ, Paola', 'Ciencia Política', NULL),
('ENCINAS ZEVALLOS, Daniel', 'Ciencia Política', 'Política Comparada'),
('AVALOS BARRIO DE MENDOZA, Vicente Daniel', 'Ciencia Política', 'Pensamiento Social Contemporáneo'),
('GODOY MEJIA, Jose Alejandro', 'Ciencia Política', 'Investigación Académica'),
('NOLES COTITO, Mariela Ines', 'Ciencia Política', NULL),
('BARRENECHEA CARPIO, Rodrigo', 'Ciudadanía y Democratización', 'Poder e Instituciones'),
('CHENG MATSUNO, Vanessa Cecilia', 'Contemporary Public Administration Seminar', NULL),
('TACUCHE MORENO, Luis Enrique', 'Discriminación y Políticas Públicas', NULL),
('SANBORN , Cynthia Ann', 'Economía Politica Internacional', NULL),
('FLORES NORIEGA DE BENITES, Eva Paulina', 'Investigación Académica', NULL),
('DEBENEDETTI LUJAN, Bruno Edoardo', 'Investigación Académica', 'Destrezas Legales I, Sem. de Tesis'),
('GIESECKE CHERO, Micaela', 'Investigación Académica', NULL),
('CASTILLO THORNE, Krishna David', 'Investigación Académica', 'Sociología'),
('DEL MASTRO VECCHIONE, Marco Hugo', 'Investigación Académica', 'Pensamiento Social Contemporáneo'),
('SETLAK , Magdalena Anna', 'Investigación Académica', NULL),
('GUTIERREZ COTTLE, Maria Cristina', 'Investigación Académica', NULL),
('VALLEJO RIVERA, Elizabeth Rocio', 'Investigación Académica', NULL),
('GORENSTEIN RIVERA, SHARON', 'Investigación Académica', NULL),
('PIZARRO BAUMANN, Maria Jimena', 'Investigación Académica', NULL),
('STIGLICH VARGAS, Maria Elizabeth', 'Investigación Académica', 'Sicología'),
('CRUZADO SILVERII, Miguel Gabriel', 'Pensamiento Social Contemporáneo', NULL),
('KOGAN COGAN, Liuba', 'Pensamiento Social Contemporáneo', NULL),
('PROTZEL DE AMAT, Jaime Javier', 'Pensamiento Social Contemporáneo', NULL),
('PEREZ RECALDE , Guadalupe', 'Pensamiento Social Contemporáneo', 'Procesos sociopolíticos de América Latina a través del Cine, Sociología'),
('MARIANI , Santiago', 'Procesos sociopolíticos de América Latina a través del Cine', NULL),
('PEÑA ANAYA, Maria Luisa', 'Proyección Social', NULL),
('VARELA GARCIA, Cinthia Patricia Alexandra', 'Proyección Social', NULL),
('VIDAL IZAGUIRRE, Patricia Estela', 'Proyección Social', NULL),
('ZUÑIGA BRAVO, Martha Eliana', 'Proyección Social', NULL),
('FLORES GUZMAN, ROSIO MILAGRO', 'Proyección Social', NULL),
('BAMBAREN LUKIS, Fernando Armando', 'Relaciones Internacionales', NULL),
('MENESES GONZALES, Gonzalo Alfredo', 'Sicología', NULL),
('RODRIGUEZ CUADROS DE MURO, Lorena', 'Sicología', NULL),
('YOSHIDA GOTO, Erika', 'Sicología', NULL),
('OTINIANO CAMPOS, Fiorella', 'Sicología', NULL),
('SOLANO SILVA, Dante Junior', 'Sicología', NULL),
('BIELICH SALAZAR, Claudia Teresa', 'Sociología', NULL),
('COBIAN OVALLE DE PLAZA, Maria Beatriz', 'Sociología', NULL),
('MEDRANO GARCIA, Fabricio Manuel', 'Aspectos Jurídicos para los Negocios', 'Derecho Laboral y Tributario'),
('PANTIGOSO VELLOSO DA SILVEIRA, Francisco', 'Aspectos Tributarios para la Empresa', 'Derecho Laboral y Tributario'),
('DE LA TORRE ONOFRE, Christian Raul', 'Auditoría', NULL),
('SOTO MUJICA, José Carlos Humberto', 'Constitución y Formalización de MYPES', 'Fundamentos de Contabilidad'),
('ALVA GONZALES, Edgar Paul', 'Contabilidad de Costos', 'Contabilidad de Gestión'),
('YAÑEZ QUIROZ, Mario Alberto', 'Contabilidad Financiera Aplicada', 'Fundamentos de Contabilidad'),
('JARA MIRANDA, Renan Geoffrey', 'Contabilidad Financiera Intermedia', NULL),
('CHONG LEON, Esteban', 'Contabilidad Financiera Intermedia', NULL),
('QUEVEDO ALEJOS, Maria Isabel Alejandra', 'Contabilidad Financiera Intermedia', NULL),
('ASTORGA DE LA CRUZ, Brandelt Jesús', 'Contabilidad Financiera Intermedia', 'Investigación para Contadores'),
('MARADIEGUE , SANTIAGO ALBERTO', 'Contabilidad Financiera Intermedia', NULL),
('ROSAS AMBROSIO, Annel Victoria', 'Contabilidad Financiera Intermedia', NULL),
('ARIAS PICON, Norma Beatriz', 'Contabilidad Financiera Intermedia', 'Fundamentos de Contabilidad, Management Accounting'),
('CACERES LOAYZA, Rosa Graciela', 'Contabilidad Financiera Intermedia', 'Fundamentos de Contabilidad'),
('RUIZ HURTADO, Pedro Cesar', 'Contabilidad Financiera Intermedia', 'Evaluación Financiera de las Organizaciones, Evaluación Financiera para No Contadores'),
('ESCOBAR ESPINO, Roberto Diego', 'Contabilidad para la Toma de Decisiones', 'Fundamentos de Contabilidad'),
('SILVA TORRALVA, Hans Jhordan', 'Contabilidad para la Toma de Decisiones', 'Fundamentos de Contabilidad, Gestión y Costos Estratégicos'),
('MATEO UNCHUPAICO, Maria Victoria', 'Contabilidad para la Toma de Decisiones', NULL),
('LOMBARDI VALLE, GINA ANGELA', 'Contabilidad para la Toma de Decisiones', NULL),
('ONTON LOPEZ, Renzo Jesus', 'Contabilidad y Finanzas Avanzadas', NULL),
('RUIZ LLACSAHUANGA, Ketty Margarita', 'Control Interno y Gestión de Riesgo', NULL),
('RUIZ PALOMINO, Cesar', 'Evaluación Financiera de las Organizaciones', NULL),
('CASTELLANOS NAVARRETE, Laura Mariela', 'Evaluación Financiera de las Organizaciones', NULL),
('ABREGU NAVEROS, Johana', 'Evaluación Financiera de las Organizaciones', NULL),
('RIVERO PONCE DE LEON, Eduardo Ruben', 'Fundamentos de Contabilidad', NULL),
('CHAVEZ CARDEÑA, Cesar Augusto', 'Fundamentos de Contabilidad', NULL),
('ZELADA ROLLER, Vilma Francisca', 'Fundamentos de Contabilidad', NULL),
('QUIÑONES BOZA, Horacio', 'Fundamentos de Contabilidad', NULL),
('MATSUNO FUCHIGAMI, Ana Cecilia', 'Fundamentos de Contabilidad', 'Principle of Accounting'),
('VELASQUEZ RELAYZE, Jose Luis', 'Gestión de la Información y Métricas de Sostenibilidad Empresarial', NULL),
('BENAVIDES GONZALES, Javier Arturo', 'Inteligencia Artificial Generativa Aplicada a la Información Financiera', 'Valoración Estratégica de Intangibles y Activos del Conocimiento'),
('BAAKLINI , Pascale', 'International Financial Reporting', NULL),
('ZEGARRA BENAVIDES, Carmen Cecilia', 'Normas Contables Internacionales', NULL),
('GARCIA REYES, Karin Maria', 'SAP Hana para la Gestión de la Información', NULL),
('CASTRO ARANA, Javier', 'Tributación Aplicada I', NULL),
('QUISPE CHUMPE, Emerzon', 'Tributación Aplicada II', NULL),
('LLONTOP MEJIA, Miguel Angel', 'Agentes Inteligentes', 'Gestión de Proyectos'),
('ROJAS VILLANUEVA, Uwe', 'Algoritmos y Estructura de Datos', 'Herramientas de Programacion con Python, Principios de Machine Learning, Técnicas Avanzadas para el Análisis de Datos'),
('FABIAN ARTEAGA, Junior John', 'Analítica de la Web', 'Deep Learning, Ingeniería de Datos, SQL para la Toma de Decisiones'),
('TOVAR GALARRETA, Juan Carlos', 'Big Data Analytics', 'Computación de Alto Desempeño y Cloud Computing'),
('AMADO GARFIAS, Alonso', 'Business Analytics', 'Infraestructura Tecnológica, Machine Learning'),
('WAM BALTODANO, Javier Guillermo', 'Business Intelligence', NULL),
('AGUIRRE RUIZ, Jose Jonathan', 'Ciberseguridad', NULL),
('ESPEZUA LLERENA, Soledad', 'Data Mining', 'Nivelación en Informática'),
('VALERA GARCIA, Paulo Enrique', 'Desarrollo de Soluciones Empresariales', 'Infraestructura Tecnológica, Ingeniería de Datos'),
('HUAMAN LINARES, Jose', 'Desarrollo de Soluciones Empresariales', NULL),
('WONG POGGI, Jennifer Karina', 'Design Thinking and Technological Innovation', 'Metodologías Ágiles'),
('HIUMETTRI BLANCO, Victor Kervin', 'Design Thinking and Technological Innovation', 'Emprendimiento Tecnológico, Innovación, Tecnologías y Emprendimiento: El caso de Silicon Valley, Metodologías Ágiles, Marketing Digital y Redes Sociales'),
('RAMIREZ VINATEA, Jimena', 'Design Thinking and Technological Innovation', NULL),
('MARTINEZ QUIÑE, Lourdes', 'Design Thinking and Technological Innovation', NULL),
('FANG CHONG, Sergio Enrique', 'Emprendimiento Tecnológico', 'Trabajo Final de Ingeniería Empresarial'),
('LAZARTE AGUIRRE, Luz Andrea', 'Emprendimiento Tecnológico', NULL),
('DIAZ DOMINGUEZ, Carlos Manuel', 'Excel Avanzado para la Gestión Empresarial', 'Nivelación en Informática'),
('STUCCHI PORTOCARRERO, Luciano', 'Física', NULL),
('CARBAJAL VIGO, Saneli Alcides', 'Física', 'Introducción a la Cosmología y la Ciencia de la Vida, Pensamiento Sistémico'),
('QUIROZ GONZALEZ, Jorge Luis Martín', 'Física', NULL),
('LAZO LAZO, Juan Guillermo', 'Formulación y Evaluación de Proyectos', 'Investigación de Operaciones'),
('GONZALEZ PALOMINO, JORGE MARTIN', 'Formulación y Evaluación de Proyectos', NULL),
('MAEHARA ALIAGA DE BENITES, Rocio Paola', 'Fundamentos de Analítica', NULL),
('CUMPA OBREGON, Nelson Enrique', 'Gerencia de Ingeniería de Valor', 'Inteligencia Artificial Aplicada a la Cadena de Suministros, Procesos de Distribución, Procesos de Producción'),
('STUART ALVARADO, Maria Gabriela', 'Gerencia de Ingeniería de Valor', NULL),
('PALOMINO GARCIA, Jorge Ciro', 'Gestión de Proyectos', NULL),
('AYMA QUIRITA, Victor Hugo', 'Herramientas de Programación', NULL),
('MUÑOZ CASILDO, Nehil Indalicio', 'Herramientas de Programación', 'Ingeniería de Datos'),
('QUISPE AYALA, Martha Roxana', 'Herramientas de Programación', 'Nivelación en Informática'),
('SIERRA FLORES, Luis Miguel', 'Herramientas de Programación', 'Investigación de Operaciones'),
('CARRILLO THORNE, Juan Diego', 'Historia Crítica del Diseño', NULL),
('SICCHA AYVAR, Hobber Aristides', 'Infraestructura Tecnológica', NULL),
('GARMENDIA FOSSA, Francisco Antonio', 'Ingeniería de Procesos', 'Procesos de Suministros, Trabajo Final de Ingeniería Empresarial, Gestión Internacional de Empresas'),
('CHICHIZOLA PORRAS, Victor Augusto', 'Ingeniería de Procesos', NULL),
('TALAVERA LOPEZ, Alvaro Gustavo', 'Inteligencia Computacional', 'Trabajo Final de Ingeniería de la Información I'),
('RODRIGUEZ SATIZABAL, Simon Andres', 'Introducción a la Cosmología y la Ciencia de la Vida', NULL),
('PELAYO BALDARRAGO, Mara Elizabeth', 'Introducción a la Cosmología y la Ciencia de la Vida', NULL),
('CHONG CHONG, Mario Gustavo', 'Introducción a la Ingeniería', 'Procesos de Distribución'),
('ORTIZ VALENCIA, Alejandro Leopoldo', 'Introducción a la Ingeniería', 'Metodologías Ágiles, Transformación Digital y Gestión del Cambio'),
('MACHUCA DE PINA, Juan Manuel', 'Investigación de Operaciones', 'Matemáticas Discretas para la Computación'),
('LIBAQUE SAENZ, Christian Fernando', 'Métodos de Investigación Cuantitativa', NULL),
('BRAVO ORELLANA, Edgardo Ricardo', 'Métodos de Investigación Cuantitativa', NULL),
('SENMACHE SARMIENTO, Jose Manuel Martin', 'Nivelación en Informática', NULL),
('ZALDIVAR PEÑA, Doris Adriana', 'Nivelación en Informática', NULL),
('TORRES SUAREZ, Rolando Martin', 'Nivelación en Informática', NULL),
('PÉREZ - GODOY BALLÓN, Luis Alberto', 'Pensamiento Sistémico', NULL),
('SALCEDO MANSILLA, Jorge Manuel', 'Procesos de Producción', NULL),
('RIVERO CESPEDES, Luis Felipe', 'Procesos de Producción', NULL),
('CORNEJO RIVERO, Alvaro Alexander', 'Prototipea tu Idea con Impresión 3D', NULL),
('SZOSTEK , Agnieszka', 'Sem. Defining Powerful Experience Strategy', NULL),
('JURBURG MELNIK, Daniel Andres', 'Sem. Defining Powerful Experience Strategy', NULL),
('FLORCZAK , Waldemar Han', 'Sem. Introduction to Operational Research', NULL),
('LUNA , Ana Eugenia', 'Tecnología para el Desarrollo Sostenible', NULL),
('SOTOMAYOR CABRERA, Aristides', 'Tecnología para el Desarrollo Sostenible', NULL),
('RODRIGUEZ SERRA, Michelle', 'Tecnología y Negocios Digitales', NULL),
('DROGUETT QUEZADA, Nicolas Patricio', 'Tecnología y Negocios Digitales', NULL),
('HAAKER MASSA, Aisa', 'Tecnología y Negocios Digitales', NULL),
('ALIAGA ALIAGA, Walter', 'Trabajo Final de Ingeniería Empresarial', NULL),
('RETAMOZO ESCOBAR, Jaliya', 'Acto Jurídico', 'Responsabilidad Extracontractual'),
('CHAVEZ VERASTEGUI, Christian', 'Acto Jurídico', NULL),
('PIEROLA CASTRO, Noe Fernando Nicolas', 'AI Regulation: A Global and Comparative Perspective', NULL),
('ZUÑIGA PALOMINO, Mario Augusto', 'Análisis Económico del Derecho', NULL),
('ESPEJO DONAIRE, Andrea Patricia', 'Arbitraje', NULL),
('TOVAR GIL, Maria Del Carmen Violeta', 'Arbitraje', NULL),
('FERRERO DIAZ, Javier Ignacio', 'Arbitraje', NULL),
('HUANCO PISCOCHE,', 'Arbitraje', NULL),
('HUANCO PISCOCHE, Henry Wilder', 'Contratos', 'Derechos Reales'),
('MADRID HORNA, Victor', 'Contratos', 'Obligaciones'),
('SORIA AGUILAR, Alfredo Fernando', 'Contratos Especiales', NULL),
('GABRIEL RIVERA, Jose Luis', 'Contratos Especiales', 'Economía y Derecho'),
('VASQUEZ REBAZA,', 'Contratos Especiales', NULL),
('NUÑOVERO CISNEROS, Lucia Betty', 'Criminología y Derecho Penitenciario', NULL),
('PEREZ', 'Criminología y Derecho Penitenciario', NULL),
('TIRADO BARRERA, Jose Antonio', 'Derecho Administrativo I', NULL),
('GOMEZ APAC, Hugo Ramiro', 'Derecho Administrativo I', NULL),
('MORI TORRES, Natalia Vanessa', 'Derecho Administrativo II', NULL),
('FARFAN SOUSA, Ronnie Ado', 'Derecho Administrativo II', 'Sem. de Derecho Administrativo y Regulación'),
('ARMESTAR BRUNO, Gloria Maria', 'Derecho Civil y Comercial', NULL),
('RAMIREZ OTERO, Lorena Cecilia', 'Derecho Civil y Comercial', 'Sociedades'),
('PARODI LUNA, Maria Beatriz', 'Derecho Civil y Comercial', NULL),
('FERRANTE , Alfredo', 'Sem. Derecho Comparado: Aspectos Prácticos y Metodológicos', NULL),
('LIZARRAGA VERA-PORTOCARRERO, Anthony', 'Derecho Concursal', NULL),
('ALBAN GONZALEZ, Javier Ignacio', 'Derecho Constitucional General', 'Derecho Procesal Constitucional'),
('NEYRA ZEGARRA, Ana Cristina', 'Derecho Constitucional General', NULL),
('PLACIDO VILCACHAGUA, Alex Fernando', 'Derecho de Familia y Sucesiones', NULL),
('MARES RUIZ, Carla Elena', 'Derecho de la Empresa', 'Derecho Tributario I'),
('RUIZ COLMENARES,', 'Derecho de la Empresa', NULL),
('VASSALLO BURNEO, Nicolas', 'Derecho Internacional Privado', NULL),
('ZELADA ACUÑA, Carlos Joel', 'Derecho Internacional Público', NULL),
('PRELLE MAYURI, Herbert Victor Ricardo', 'Derecho Laboral I', NULL),
('TOYAMA MIYAGUSUKU, Jorge Luis', 'Derecho Laboral I', NULL),
('CASTILLO FUENTES, Diego Sebastian', 'Derecho Laboral I', NULL),
('LORA ALVAREZ, German Lino', 'Derecho Laboral I', 'Derecho Laboral y Tributario'),
('CASTRO POSADAS, Eric Christian', 'Derecho Laboral II', NULL),
('GILDEMEISTER RUIZ HUIDOBRO, Alfredo', 'Derecho Laboral y Tributario', NULL),
('SALAZAR TIRADO,', 'Derecho Laboral y Tributario', NULL),
('GARCIA BELAUNDE SALDIAS, Diego', 'Derecho para los Negocios Internacionales', 'Negociaciones Comerciales Internacionales'),
('CARO JOHN, Jose Antonio', 'Derecho Penal', NULL),
('REAÑO PESCHIERA, José', 'Derecho Penal', NULL),
('BENDEZU BARNUEVO, Rocci Fiorella', 'Derecho Penal', 'Derecho Penal Económico'),
('CUBA COPELLO, YVO CAMILO', 'Derecho Procesal Civil', NULL),
('RIVAS CASO, Gino Elvio', 'Derecho Procesal Civil', NULL),
('CAMPOS BERNAL, Heber Joel', 'Derecho Procesal Constitucional', NULL),
('CAYO RIVERA SCHREIBER, Maria Jimena Soledad /', 'Derecho Procesal Penal', NULL),
('DIAZ TENORIO, Diego Arturo', 'Derecho Tributario I', NULL),
('HUERTAS LIZARZABURU, Martha Cristina', 'Derecho Tributario I', NULL),
('POLO CHIROQUE, ROBERTO EDWARD', 'Derecho Tributario II', NULL),
('RUIZ COLMENARES, Melissa Sarahi', 'Derecho Tributario II', NULL),
('RAVINA SANCHEZ, Raul Fernando', 'Derechos Reales', NULL),
('GINES CASTELLET, Nuria', 'Derechos Reales y Contratos: Teoría Clásica y Transformaciones Contemporáneas', NULL),
('ALONSO HERRERA, Jorge Ivan', 'Destrezas Legales y Económicas para Litigar en Libre Competencia', NULL),
('ZUÑIGA PALOMINO,', 'Destrezas Legales y Económicas para Litigar en Libre Competencia', NULL),
('URBINA LOVON, Erick Edwin', 'Economía y Derecho', NULL),
('IPARRAGUIRRE ROMERO, Gianfranco', 'Economía y Derecho', NULL),
('LEON LUNA,', 'Economía y Derecho', NULL),
('COGORNO FALCONE, Sandro Agustin', 'Fusiones y Adquisiciones', NULL),
('CORTINA MENDOZA, Roxana Marina', 'Inglés Jurídico', NULL),
('BARDALES MENDOZA, Enrique Rosendo', 'Instituciones de Derecho Mercantil', NULL),
('ZUÑIGA SCHRODER, Humberto Angel', 'Introducción al Derecho', NULL),
('OLIVOS CELIS, Milagros Katherine', 'Introducción al Derecho', 'Personas del Derecho Civil'),
('TALAVERA CANO, Andres Alvaro', 'Introducción al Derecho', NULL),
('VASQUEZ REBAZA, Walter Humberto', 'Obligaciones', NULL),
('BRAVO ARANA, Grismi Claudia', 'Organizaciones Internacionales', NULL),
('CLAROS ABARCA, Roberto Fernando', 'Organizaciones Internacionales', NULL),
('NEIRA LUCAR, Melissa Judith', 'Personas del Derecho Civil', NULL),
('ALIAGA FARFAN, Jeanette Sofia', 'Regulación Bancaria y Mercado de Capitales', NULL),
('ABAD YUPANQUI, Samuel Bernardo', 'Sem. de Derecho Constitucional', NULL),
('FREITAS CABANILLAS, Rodrigo Andrés', 'Técnicas de Persuasión y Moot Court', NULL),
('HUANCO', 'Técnicas de Persuasión y Moot Court', NULL),
('REAÑO PESCHIERA, José Leandro', 'Tendencias Jurisprudenciales del Derecho Penal Económico', NULL),
('SIMONS PINO, Adrian Marcius', 'Teoría General del Proceso', NULL),
('CHIRINOS VIDAURRAZAGA, Gonzalo Guillermo', 'Teoría General del Proceso', NULL),
('MALPARTIDA TABUCHI, Daniel Humberto', 'Análisis Financiero', NULL),
('LUNA VICTORIA CONTRERAS, Rolando Alfonso', 'Análisis y Gestión de Riesgos', NULL),
('RAUNELLI MONTERO, Jose Carlos', 'Análisis y Gestión de Riesgos', 'Finanzas Cuantitativas, Fundamentos de Finanzas'),
('MONGRUT MONTALVAN, Samuel Arturo', 'Economía Financiera I', 'Finanzas Corporativas II'),
('CARBAJAL ZAPATA, Jeferson Davy', 'Economía Financiera I', NULL),
('CORNEJO LIMO, Luis Bruno', 'Economía Financiera I', NULL),
('POZO SANCHEZ, Jorge Antonio', 'Economía Financiera II', NULL),
('WATSON ALVARADO, Jean Paul', 'Economía Financiera II', NULL),
('DEFILIPPI ANGELDONIS, Enzo Fabrizio', 'Finanzas Corporativas I', 'Renta Variable'),
('YAMAN , Serhat', 'Finanzas Corporativas I', 'Renta Fija'),
('ROBLES FLORES, Luis Miguel', 'Finanzas Corporativas I', 'Fundamentos de Finanzas'),
('PANDURO PARDO, Julio Antonio', 'Finanzas Corporativas I', NULL),
('CORDOVA LOPEZ, Juan Pablo', 'Finanzas Corporativas I', NULL),
('TELLO YZAGUIRRE, Andre Luis', 'Finanzas Corporativas I', NULL),
('RUIZ PEREZ, Jose Luis', 'Finanzas Sostenibles', 'Microeconomía Financiera'),
('RUNCIMAN SAETTONE, Guillermo Alfredo', 'Finanzas y Abundancia', NULL),
('SIANCAS SOTELO, Francis Junior', 'Fundamentos de Finanzas', NULL),
('ALVAREZ DROBUSH, Alexei Darwinovich', 'Fundamentos de Finanzas', NULL),
('CRUZ CASTAÑEDA, Vivian', 'Fundamentos de Finanzas', 'Instrumentos Derivados'),
('ARIAS VERNAL, Carlos Augusto', 'Fundamentos de Finanzas', 'Sem. de Ethics in Finance'),
('VARGAS VILCHEZ, Enver Enrique', 'Fundamentos de Finanzas', NULL),
('VAIZ NEYRA, Luis Oscar', 'Fundamentos de Finanzas', NULL),
('ARCE ROEL, Luis Enrique', 'Fundamentos de Finanzas', NULL),
('DOOR OSELE, Daniela', 'Fundamentos de Finanzas', NULL),
('TAM CUBA, Sasha Prince', 'Fundamentos de Finanzas', NULL),
('QUEVEDO SANCHEZ, Gregorio Vladimir', 'Fundamentos de Finanzas', 'Sem. Valorización de Empresas'),
('GABILONDO ALVAREZ, Sergio Alejandro', 'Gestión Financiera', 'Proyectos de Inversión'),
('LLADO MARQUEZ, Jorge Eduardo', 'International Finance', NULL),
('VILLAFUERTE', 'International Finance', NULL),
('MENDIBURU DIAZ, Carlos Hugo', 'Macroeconomía Financiera', NULL),
('OGATA SHIMOKAWA DE KANAMORI, Clara Elena', 'Mercado de Capitales', NULL),
('CASTELLANOS ROBLES, Enrique Guillermo', 'Negociación Financiera', 'Riesgo Crediticio'),
('RODRIGUEZ CASANOVA, Gianina', 'Negociación Financiera', NULL),
('VALENZUELA HUARCAYA, Adriana', 'Riesgo Crediticio', NULL),
('DE LA CUBA RESTANI, Mauricio Fernando', 'Sem. Crisis Financiera Internacional', NULL),
('BERGGRUN PRECIADO, Luis', 'Sem. Cuantitativo de Riesgo Crediticio', NULL),
('SANCHO ROJAS, Alejandro Antonio', 'Seminario de Administración de Riesgo en Banca', NULL),
('TANTALEAN VALDIVIESO, Elizabeth Marie', 'Sem. de Alternative Investment', NULL),
('MONTENEGRO LEE, Ruben Angel', 'Sem. de Dark Finance', NULL),
('OLIVARES CANCHARI, Jose Andres', 'Sem. de Estrategias de Fondeo', NULL),
('TORRES GOMEZ, Victor Manuel', 'Sem. de Financial Modeling', NULL),
('DIAZ GALINDO, Fanny Mariana', 'Sem. de Fintech', NULL),
('RUIZ DE LA CRUZ, Fernando Miguel', 'Sem. de Leveraged Buyouts', NULL),
('LAU PUN, Federico', 'Sem. de Project Finance', NULL),
('MATUTE QUIROGA, Juan Andres', 'Sem. de Sports Finance', NULL),
('PONCE HEREDIA, Juan Jose', 'Sem. Investments Tools and Case Studies', NULL),
('LUCEN VALDIVIA, Fernando', 'Sem. Real Estate', NULL),
('SANCHEZ CHAVEZ, Elio Javier', 'Sem. Sistema de Pensiones', NULL),
('LEON , Vicente Manuel', 'Sistemas Financieros', NULL),
('LIZARZABURU BARTRA, Adriana Lastenia', 'Sistemas Financieros', NULL),
('PANCORBO VALDIVIA, Sergio Omar', 'Sistemas Financieros', NULL),
('MOSQUEIRA LOAYZA, Javier Edilberto', 'Account Management - Gestión de Clientes Clave', NULL),
('PEINADO BRAVO, Maria Estrella Del Pilar', 'Administración del Comercio Internacional', 'Fundamentos Económicos y Organizacionales para los Negocios'),
('HERNANI MERINO, Martin Nelson', 'Comportamiento del Consumidor', 'Investigación en Marketing I'),
('KOBAYASHI ANDO, María Elena', 'Cross Cultural & International Management', NULL),
('PINTO GUILLEN, Maria Jose', 'Cross Cultural & International Management', NULL),
('MALCA GUAYLUPO, Oscar Enrique', 'Dirección Internacional de Empresas', 'Estrategias de Internacionalización'),
('MONGE VARGAS, Mariana', 'Diseño Conductual', NULL),
('ESPINOZA MATOS, José Francisco', 'E-commerce', NULL),
('CARBONELL ROSSO, María De Las Mercedes', 'Estrategias de Branding', 'Marketing Sostenible, Pricing'),
('LIZARZABURU VELASQUEZ, Carlos Enrique', 'Estrategias de Comunicación y Promoción', NULL),
('PENNANO VILLANUEVA, Carla', 'Fundamentos de Marketing', 'International Marketing, Marketing Estratégico'),
('RIVAS VELARDE,', 'Fundamentos de Marketing', NULL),
('POZO YABAR, Natalia Sofia', 'Gestión Comercial', NULL),
('MEUNIER , Bernard', 'Gestión de Mercados Globales', NULL),
('SAKODA MIZUSHIMA, Diego', 'Gestión de Productos', NULL),
('LADINES AZALIA, Juan Carlos', 'Gestión del Comercio Internacional', 'International Affairs'),
('GARCIA JERI, Oswaldo Carlos', 'Gestión del Comercio Internacional', 'Gestión Internacional de Empresas'),
('ARRIETA PADILLA, Gabriel Lewis', 'Gestión del Comercio Internacional', 'Teoría del Comercio Internacional y Procesos de Integración'),
('PEREZ DE ARMAS, Emilio', 'Gestión Estratégica Comercial, Métricas y Ética', NULL),
('ACOSTA RUIZ, Vanessa Mirtha', 'Gestión Internacional de Empresas', 'Global Branding'),
('MORI CLEMENT, Yadira Isbi', 'Gestión Sostenible de la Oferta Exportable', NULL),
('DEL SOLAR ESCARDO, Diego', 'Global Food & Agribusiness Strategies', NULL),
('VEGA FARRO, Elizabeth', 'Growth Hacking', NULL),
('EDEH , Jude Ndubuisi', 'Innovation, Competitiveness & Export Performance', NULL),
('LIMONGI FRANCA COELHO, Ricardo', 'Intelligent Marketing: Creativity and Innovation in the Age of AI', NULL),
('CALMET GUTIERREZ, Maria Angela', 'Intercultural Competence', NULL),
('VARGAS DE LA JARA, Marisol', 'International Affairs', NULL),
('DIAZ DIAZ, Dagoberto Luis', 'International Business Plan', NULL),
('ALVARADO RUIZ, Paola Alessandra', 'International Business Plan', NULL),
('KALMURAND , Katrin', 'International Human Resources Management', NULL),
('CARRERAS MERINO, Andrea', 'International Human Resources Management', NULL),
('MELLADO SILVA, Maria Antonieta Rosario', 'Investigación de Mercados', NULL),
('TALAVERA SALDARRIAGA, Willy Martin Enrique', 'Investigación de Mercados', NULL),
('ZUÑIGA LAZO, Jenny Lorena', 'Investigación de Mercados', NULL),
('TUTAYA ZEVALLOS, Renan Jesus', 'Investigación de Mercados', 'Marketing Estratégico'),
('GOMEZ ALVIS, ELIZABETH INGRID', 'Investigación de Mercados', NULL),
('MANRIQUE PONCE, Christian Gerardo', 'Marketing B2B', 'Marketing de Contenido, Métricas y Analítica de Marketing'),
('CLAUX FREITAS, Lorena', 'Marketing de Servicios', NULL),
('MAYORGA GUTIERREZ, David Jesus', 'Marketing Estratégico', 'Plan de Marketing'),
('FELICIANO NISHIKAWA, Jose Carlos', 'Marketing Internacional en China y Asia-Pacífico', NULL),
('GONZALES ARBAIZA, Maricruz Del Pilar', 'Marketing Personal para el Mundo Labóral', NULL),
('SCHWALB HELGUERO, Maria Matilde', 'Marketing Sostenible', NULL),
('ROMAN YSEKI, Jorge Hiroshi', 'MVPs and Innovation for Global Markets', NULL),
('MARROU LOAYZA, Julio Estuardo', 'Pensamiento Crítico para Marketing', NULL),
('DE VEGA DE UNCETA, Alejandro', 'Storytelling: Cómo conectar emocionalmente con los consumidores a través de las historias', NULL),
('BRAGAGNINI OLIVER, Rizal Andres', 'Trade Marketing', NULL);

UPDATE professors p
SET 
  especialidad = t.especialidad,
  otros_cursos = t.otros_cursos
FROM temp_prof_updates t
WHERE UPPER(TRIM(p.nombre)) = UPPER(TRIM(t.nombre));
DROP TABLE temp_prof_updates;
