
CREATE TEMP TABLE temp_prof_updates (
  nombre text,
  especialidad text,
  otros_cursos text
);
INSERT INTO temp_prof_updates (nombre, especialidad, otros_cursos) VALUES
('PARDO GRAU, Cecilia Maria Luisa', 'Antiguo Perú, Arqueología, Museos y Nuevas Tecnologías', 'Arte y diseño prehispánico. Naturaleza y legado, Introducción a las Humanidades Digitales'),
('DEL MASTRO PUCCIO, Cesare Anibal', 'Antropología Filosófica', 'Filosofía, Introducción a la Política, Filosofia y Economía'),
('ESPINOSA WINDER, Francisco', 'Comunicación Digital', 'Lectura Crítica de la Prensa Digital y en las Redes Sociales'),
('PIEDRA VALDEZ, Jose Leopoldo', 'Dios, Existencia Humana y Sociedad', 'Ética'),
('VARGAS DELLA CASA, Rosa Elvira', 'Ética', NULL),
('QUIROZ MEZA, Danitza Dejanira', 'Ética', 'Filosofía'),
('PONCE BOGINO, Hector Alberto', 'Ética', NULL),
('EGOAVIL RIOS, Jean Christian', 'Ética', NULL),
('HINOSTROZA RIVERA, Dino Arturo', 'Ética', NULL),
('IVANOFF SABOGAL, Christian', 'Ética', NULL),
('ARANA ALENCASTRE, Jean Luis', 'Ética', NULL),
('VILLARAN CONTAVALLI, ALONSO MANUEL', 'Ética', NULL),
('DEXTRE UZATEGUI, Sergio Guillermo', 'Ética', 'Filosofía'),
('MORENO GONZALEZ, Rafael', 'Ética', 'Filosofía'),
('CARRIÓN CARAVEDO, Úrsula', 'Filosofía', 'Filosofia Política, Lenguaje II'),
('LASTRES DAMMERT, Pamela Maria', 'Filosofía', NULL),
('IBAÑEZ BLANCAS, Franklin Ernesto', 'Filosofía', NULL),
('ASTUDILLO TORRES, Deyvi Harold', 'Filosofía', NULL),
('FONSECA ARIZA, Juan Adoniran', 'Historia Crítica del Perú', 'Religiones, Culturas y Economía'),
('INJOQUE RONCEROS, Freddy Miguel', 'Historia Crítica del Perú', 'Pensamiento Social Contemporáneo, Análisis de Datos Geográficos'),
('LIZARME VILLCAS, Nashely Yuvitza', 'Historia Crítica del Perú', NULL),
('MONSALVE ZANATTI, Martin Alberto', 'Historia Económica del Perú', 'Historia y Filosofía de la Ciencia'),
('CAMACHO GAVIDIA, Abel Fernando', 'Historia Económica del Perú', 'Historia Económica y Empresarial'),
('CASAS TRAGODARA, Carlos Augusto', 'Historia Económica del Perú', 'Econometría II, Macroeconomía de Corto Plazo, Macroeconomía III'),
('RODRIGUEZ SATIZABAL, Beatriz Helena', 'Historia Económica y Empresarial', NULL),
('CARRASCO WESTON, Jose Manuel', 'Historia Económica y Empresarial', NULL),
('BARRETO VELAZQUEZ, Norberto', 'Historia Económica y Empresarial', NULL),
('CABREJOS PORTOCARRERO, Jose Ignacio', 'Historia Económica y Empresarial', NULL),
('PEREZ MARTINEZ, Angel Ruben', 'Historia y Filosofía de la Ciencia', NULL),
('GUADALUPE MENDIZABAL, Cesar Augusto', 'Historia y Filosofía de la Ciencia', NULL),
('BARRON AYLLON, Manuel Fernando', 'Introducción a la Política, Filosofia y Economía', 'Econometría I, Microeconomía II'),
('PEREZ , Leda Margarita', 'Introducción a la Política, Filosofia y Economía', NULL),
('NASSI PERIC, Bruno Fernando', 'Lenguaje I', 'Lenguaje II'),
('LANDA ROJAS, Luis Enrique', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('QUIROZ VELA, Juan Enrique', 'Lenguaje I', 'Nivelación en Lenguaje'),
('MORIMOTO SONE, Maria Lourdes', 'Lenguaje I', NULL),
('MONTAUBAN DEL SOLAR, Michele Marie', 'Lenguaje I', NULL),
('GAUGER QUIROZ, Juan Manuel', 'Lenguaje I', 'Nivelación en Lenguaje'),
('PINASCO ESPINOSA, Sandra Gabriella', 'Lenguaje I', NULL),
('HELGUERO MORALES, Lorenzo Pedro', 'Lenguaje I', 'Lenguaje II'),
('MADALENGOITIA BARUA, Maria Gracia', 'Lenguaje I', 'Nivelación en Lenguaje'),
('PEREZ DEL SOLAR TOLA, Pedro Carlos Hilarion', 'Lenguaje I', 'Lenguaje II'),
('CALDERÓN BAIOCCHI, Juan Humberto', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('MERINO SILICANI DE ALVAREZ, Rosanna Maria', 'Lenguaje I', 'Nivelación en Lenguaje'),
('CARRILLO PASTOR, Giuliana Maria', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('GUTIERREZ MEZA, José Elías', 'Lenguaje I', NULL),
('GUICH RODRIGUEZ, Jose Abelardo', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('ZAPATA FAJARDO, Jaime Israel', 'Lenguaje I', 'Lenguaje II'),
('MORILLO SOTOMAYOR, Alex', 'Lenguaje I', 'Lenguaje II, Nivelación en Lenguaje'),
('HUATUCO POMALAZA, Rocio Milagros', 'Lenguaje II', 'Nivelación en Lenguaje'),
('SALCEDO REYES, Ana Lucia', 'Lenguaje II', NULL),
('FERRUCCI MONTOYA, Gabriela Ida', 'Lenguaje II', NULL),
('WIESSE REBAGLIATI, Jorge Raul', 'Literatura', NULL),
('GATTI MURRIEL, Carlos Antonio', 'Literatura Universal', NULL),
('VARGAS VILCA, Mariano Daniel', 'Nivelación en Lenguaje', NULL),
('ARMAS ASIN, Fernando Alberto', 'Religiones, Culturas y Economía', NULL),
('ROMERO PINTO, Ezequiel Eduardo', 'Religiones, Culturas y Economía', NULL),
('FLORES PAZ, Rafael Antonio', 'Religiones, Culturas y Economía', NULL),
('ATO DEL AVELLANAL CARRERA, Manuel Antonio', 'Religiones, Culturas y Economía', NULL),
('ARIAS CUBA, Ybeth Merly', 'Religiones, Culturas y Economía', NULL),
('CARO JAHNCKE, Andres Javier', 'Análisis Económico de la Competencia', NULL),
('ALVAREZ RODRICH, Augusto Anibal', 'Análisis Político Relevante para la Perspectiva Económica', NULL),
('GARCIA RAMOS, Yboon Victoria', 'Análisis Real y Convexo', 'Matemáticas IV'),
('QUISPE ROJAS, Alexander Wilder', 'Data Science con Python', 'Inferencia Causal y Machine Learning'),
('PRIALE UGAS, Miguel Enrique', 'Diseño y Evaluación Social de Proyectos', 'Economía General I'),
('BASURTO PRECIADO, Maria Pia', 'Econometría Aplicada', 'Econometría II'),
('CASTRO CARLIN, Juan Francisco', 'Econometría I', NULL),
('LAVADO PADILLA, Pablo Augusto', 'Econometría I', 'Econometría II'),
('GALARZA CONTRERAS, Elsa Patricia', 'Economía Ambiental Aplicada a las Políticas Públicas en el Perú', 'Microeconomía II'),
('GALARZA ARELLANO, Francisco Bruno', 'Economía Experimental', 'Microeconomía II'),
('LA SERNA STUDZINSKI, Karlos', 'Economía General I', NULL),
('PARODI TRECE, Carlos Alfredo Justo', 'Economía General I', 'Economía Peruana'),
('GÓMEZ GAMARRA DE ZEA, ZOILA DEL ROSARIO', 'Economía General I', NULL),
('MOLINA CAMPODONICO, Oswaldo', 'Economía General I', NULL),
('AGUIRRE MONTOYA, Julio Cesar', 'Economía General I', 'Organización Industrial'),
('HERNANDEZ RUBIÑOS, Mario German', 'Economía General I', NULL),
('PEREZ MALCA, Patricia Estela', 'Economía General I', NULL),
('MONTESINOS CORDOVA, Jorge Luis', 'Economía General I', 'Economía General II, Evaluación Privada de Proyectos'),
('PAREDES SALAZAR, Lizardo Emanuel', 'Economía General I', NULL),
('ARAGON PEÑALOZA, Gisella Silvana', 'Economía General I', NULL),
('FALEN ZEVALLOS, Luis Eduardo', 'Economía General I', 'Economía General II'),
('TALLEDO SANCHEZ, Jacqueline Isabel', 'Economía General I', NULL),
('RIVERA GALLEGOS, Gonzalo Javier', 'Economía General I', 'Microeconomía I'),
('HERAS RIVERA, Sissi Andrea', 'Economía General I', NULL),
('MUÑIZ CAHUANA, Graciela Rocio', 'Economía General I', NULL),
('LISBOA VASQUEZ, Claudia Paola', 'Economía General I', NULL),
('SEVERINO MUÑOZ, Renzo Cristhyan Enrique', 'Economía General I', NULL),
('SALINAS DEPAZ, Cesar Saturnino', 'Economía General II', NULL),
('FRANCO VALDIVIA, Eliana', 'Economía General II', 'Investigación Aplicada en Negocios Internacionales'),
('DIAZ GAZANI, Guillermo', 'Economía General II', NULL),
('SERVAN LOZANO, Sergio', 'Economía General II', NULL),
('VEGA DE LA CRUZ, Hugo Yamil', 'Economía General II', NULL),
('ROJAS RODRIGUEZ, CARMEN ROSA', 'Economía General II', NULL),
('GONZAGA MENA, Bruno Eduardo', 'Economía General II', NULL),
('URRUNAGA PASCO-FONT, Roberto Luis', 'Economía Pública', 'Macroeconomía I'),
('MUÑOZ BAZAN, Italo Juan Carlos', 'Economía y Estadística Aplicada al Derecho', NULL),
('ROMERO VEREAU, Daniel Alonso', 'Estadística Aplicada', NULL),
('SALINAS MORRIS, Juan Carlos', 'Estadística Aplicada', 'Análisis Financiero'),
('CHIRA BALLENA, Miguel Angel', 'Estadística Aplicada', NULL),
('TRUJILLO GALINDO, Renato Juan', 'Estadística Aplicada', NULL),
('MATEU BULLON, Pedro Fernando', 'Estadística I', 'Estadística II'),
('PEREZ SOTELO, Edisson Alonso', 'Estadística I', 'Matemáticas III, Nivelación en Matemáticas'),
('RUBIO DONET, Jorge Luis', 'Estadística I', 'Estadística II'),
('ANGELES OLIVERA, Julio Hugo', 'Estadística I', 'Estadística II'),
('SOTO RODRIGUEZ, Ivan Dennys', 'Estadística I', 'Estadística II'),
('LINDO HUERTAS, Elsa Maria', 'Estadística I', 'Estadística II'),
('TARAZONA VARGAS, Enver Gerald', 'Estadística I', 'Estadística II'),
('OSORIO MAURICIO, Lucila', 'Estadística I', NULL),
('CAYCHO HUAMANI, Jose Alberto', 'Estadística I', 'Análisis Multivariado para los Negocios, Investigación de Mercados Aplicada'),
('SILVESTRE VALER, Jim Roland', 'Estadística I', NULL),
('VALENCIA CHACON, Raphael Felix', 'Estadística I', NULL),
('FEBRES HUAMAN, Grimaldo Jose', 'Estadística I', NULL),
('SOTO RODRIGUEZ,', 'Estadística II', NULL),
('LI NING CHAMAN, Jorge Francisco', 'Evaluación Privada de Proyectos', NULL),
('KAMICHE ZEGARRA, Joanna Noelia', 'Gestión de los Recursos Naturales', NULL),
('MANRIQUE ZEDER, Liseth Cristina', 'Gestión de los Recursos Naturales', NULL),
('GUARDIA MUGURUZA, Alejandra', 'Green Growth Strategies for Peru and Latin America', NULL),
('TORRES GOMEZ, Javier Antonio', 'Historia del Pensamiento Económico', 'Macroeconomía I'),
('DEL HIERRO CARRILLO, Patricia', 'Historia del Pensamiento Económico', 'Sem. La IA y la Robótica: Ciclos Económicos, Impactos y Respuestas'),
('GONZALEZ VIGIL, Luis Fernando', 'Investigación Económica I', 'Investigación Económica II'),
('MORON PASTOR, Eduardo Andres', 'Macroeconomía I', NULL),
('CUSATO NOVELLI, Antonio', 'Macroeconomía I', NULL),
('ORTIZ SOSA, Marco Antonio', 'Macroeconomía II', NULL),
('PAWELCZAK , Jakub Mateusz', 'Macroeconomía II', NULL),
('CASTILLO AGUIRRE, Luis Eduardo', 'Macroeconomía II', NULL),
('PINZON GIRALDO, Alvaro Jose', 'Macroeconomía III', NULL),
('HERNANDEZ CALDERON, Joao Alejandro', 'Macroeconomía Internacional', NULL),
('MONTORO LLAMOSAS, Carlos Humberto', 'Macroeconomía Internacional', NULL),
('CHAVEZ SARMIENTO, Enrique Idael', 'Matemáticas I', 'Procesos Estocásticos'),
('OLANO CRUCES, Mario Fernando', 'Matemáticas I', NULL),
('FLORES SALINAS, JOSE ALBERTO', 'Matemáticas I', 'Matemáticas II, Matemáticas para los Negocios'),
('ESCUDERO ACERO, Phamela Stephany', 'Matemáticas I', 'Matemáticas para los Negocios, Nivelación en Matemáticas'),
('DAVILA QUESQUEN, Erick Nomberto', 'Matemáticas I', 'Matemáticas II'),
('PROLEON PATRICIO, DANIEL GIOVANNI', 'Matemáticas I', NULL),
('ESCALANTE HUAMANÍ, Sonia María', 'Matemáticas I', 'Matemáticas para los Negocios, Nivelación en Matemáticas'),
('GUARDALES VASQUEZ, Randdy Arturo', 'Matemáticas I', 'Nivelación en Matemáticas'),
('MOLINA TARAZONA, Lucy Smith', 'Matemáticas I', 'Matemáticas II, Nivelación en Matemáticas'),
('SINCHE CHOCCA, Nildo', 'Matemáticas I', 'Nivelación en Matemáticas'),
('ALCALDE SOSA, Jose Andres', 'Matemáticas I', 'Matemáticas III'),
('SALINAS ZAVALA, Christoper Jesus', 'Matemáticas I', 'Matemáticas II, Nivelación en Matemáticas'),
('ARREDONDO RUIZ, Manuel Jesus', 'Matemáticas I', 'Pensamiento Sistémico'),
('BUENO TANGOA, Orestes Martin', 'Matemáticas II', 'Matemáticas III'),
('CHULLUNCUY CENTENO, Andres Vicente', 'Matemáticas II', 'Nivelación en Matemáticas'),
('TORRES PEREZ, Elvis', 'Matemáticas II', NULL),
('COTRINA ASTO, John Edwin', 'Matemáticas III', 'Matemáticas IV'),
('WINKELRIED QUEZADA, Diego Martin', 'Matemáticas III', 'Investigación Financiera, Sem. Commodities & Volatility, Sem. de Proceso de Mercado'),
('VELASQUEZ CASTAÑON, Oswaldo Jose', 'Matemáticas III', 'Álgebra Líneal Aplicada, Programación Avanzada para la Ciencia de Datos'),
('MANTILLA GONZALES DE LA COTER, Eduardo Javier', 'Matemáticas IV', NULL),
('OSORIO UBALDO, Jaime', 'Matemáticas para los Negocios', 'Nivelación en Matemáticas'),
('CORTEZ VALDIVIA, Rafael Augusto', 'Microeconomía I', NULL);

UPDATE professors p
SET 
  especialidad = t.especialidad,
  otros_cursos = t.otros_cursos
FROM temp_prof_updates t
WHERE UPPER(TRIM(p.nombre)) = UPPER(TRIM(t.nombre));
DROP TABLE temp_prof_updates;
