
CREATE TEMP TABLE temp_prof_updates (
  nombre text,
  especialidad text,
  otros_cursos text
);
INSERT INTO temp_prof_updates (nombre, especialidad, otros_cursos) VALUES
('MONGRUT MONTALVAN, Samuel Arturo', 'Economía Financiera I', 'Finanzas Corporativas II'),
('CARBAJAL ZAPATA, Jeferson Davy', 'Economía Financiera I', NULL),
('CORNEJO LIMO, Luis Bruno', 'Economía Financiera I', NULL),
('POZO SANCHEZ, Jorge Antonio', 'Economía Financiera II', NULL),
('WATSON ALVARADO, Jean Paul', 'Economía Financiera II', NULL),
('DEFILIPPI ANGELDONIS, Enzo Fabrizio', 'Finanzas Corporativas I', 'Renta Variable'),
('YAMAN , Serhat', 'Finanzas Corporativas I', 'Renta Fija'),
('ROBLES FLORES, Luis Miguel', 'Finanzas Corporativas I', 'Fundamentos de Finanzas'),
('PANDURO PARDO, Julio Antonio', 'Finanzas Corporativas I', NULL),
('CORDOVA LOPEZ, Juan Pablo', 'Finanzas Corporativas I', NULL),
('TELLO YZAGUIRRE, Andre Luis', 'Finanzas Corporativas I', NULL),
('RUIZ PEREZ, Jose Luis', 'Finanzas Sostenibles', 'Microeconomía Financiera'),
('RUNCIMAN SAETTONE, Guillermo Alfredo', 'Finanzas y Abundancia', NULL),
('SIANCAS SOTELO, Francis Junior', 'Fundamentos de Finanzas', NULL),
('ALVAREZ DROBUSH, Alexei Darwinovich', 'Fundamentos de Finanzas', NULL),
('CRUZ CASTAÑEDA, Vivian', 'Fundamentos de Finanzas', 'Instrumentos Derivados'),
('ARIAS VERNAL, Carlos Augusto', 'Fundamentos de Finanzas', 'Sem. de Ethics in Finance'),
('VARGAS VILCHEZ, Enver Enrique', 'Fundamentos de Finanzas', NULL),
('VAIZ NEYRA, Luis Oscar', 'Fundamentos de Finanzas', NULL),
('ARCE ROEL, Luis Enrique', 'Fundamentos de Finanzas', NULL),
('DOOR OSELE, Daniela', 'Fundamentos de Finanzas', NULL),
('TAM CUBA, Sasha Prince', 'Fundamentos de Finanzas', NULL),
('QUEVEDO SANCHEZ, Gregorio Vladimir', 'Fundamentos de Finanzas', 'Sem. Valorización de Empresas'),
('GABILONDO ALVAREZ, Sergio Alejandro', 'Gestión Financiera', 'Proyectos de Inversión'),
('LLADO MARQUEZ, Jorge Eduardo', 'International Finance', NULL),
('VILLAFUERTE', 'International Finance', NULL),
('MENDIBURU DIAZ, Carlos Hugo', 'Macroeconomía Financiera', NULL),
('OGATA SHIMOKAWA DE KANAMORI, Clara Elena', 'Mercado de Capitales', NULL),
('CASTELLANOS ROBLES, Enrique Guillermo', 'Negociación Financiera', 'Riesgo Crediticio'),
('RODRIGUEZ CASANOVA, Gianina', 'Negociación Financiera', NULL),
('VALENZUELA HUARCAYA, Adriana', 'Riesgo Crediticio', NULL),
('DE LA CUBA RESTANI, Mauricio Fernando', 'Sem. Crisis Financiera Internacional', NULL),
('BERGGRUN PRECIADO, Luis', 'Sem. Cuantitativo de Riesgo Crediticio', NULL),
('SANCHO ROJAS, Alejandro Antonio', 'Seminario de Administración de Riesgo en Banca', NULL),
('TANTALEAN VALDIVIESO, Elizabeth Marie', 'Sem. de Alternative Investment', NULL),
('MONTENEGRO LEE, Ruben Angel', 'Sem. de Dark Finance', NULL),
('OLIVARES CANCHARI, Jose Andres', 'Sem. de Estrategias de Fondeo', NULL),
('TORRES GOMEZ, Victor Manuel', 'Sem. de Financial Modeling', NULL),
('DIAZ GALINDO, Fanny Mariana', 'Sem. de Fintech', NULL),
('RUIZ DE LA CRUZ, Fernando Miguel', 'Sem. de Leveraged Buyouts', NULL),
('LAU PUN, Federico', 'Sem. de Project Finance', NULL),
('MATUTE QUIROGA, Juan Andres', 'Sem. de Sports Finance', NULL),
('PONCE HEREDIA, Juan Jose', 'Sem. Investments Tools and Case Studies', NULL),
('LUCEN VALDIVIA, Fernando', 'Sem. Real Estate', NULL),
('SANCHEZ CHAVEZ, Elio Javier', 'Sem. Sistema de Pensiones', NULL),
('LEON , Vicente Manuel', 'Sistemas Financieros', NULL),
('LIZARZABURU BARTRA, Adriana Lastenia', 'Sistemas Financieros', NULL),
('PANCORBO VALDIVIA, Sergio Omar', 'Sistemas Financieros', NULL),
('MOSQUEIRA LOAYZA, Javier Edilberto', 'Account Management - Gestión de Clientes Clave', NULL),
('PEINADO BRAVO, Maria Estrella Del Pilar', 'Administración del Comercio Internacional', 'Fundamentos Económicos y Organizacionales para los Negocios'),
('HERNANI MERINO, Martin Nelson', 'Comportamiento del Consumidor', 'Investigación en Marketing I'),
('KOBAYASHI ANDO, María Elena', 'Cross Cultural & International Management', NULL),
('PINTO GUILLEN, Maria Jose', 'Cross Cultural & International Management', NULL),
('MALCA GUAYLUPO, Oscar Enrique', 'Dirección Internacional de Empresas', 'Estrategias de Internacionalización'),
('MONGE VARGAS, Mariana', 'Diseño Conductual', NULL),
('ESPINOZA MATOS, José Francisco', 'E-commerce', NULL),
('CARBONELL ROSSO, María De Las Mercedes', 'Estrategias de Branding', 'Marketing Sostenible, Pricing'),
('LIZARZABURU VELASQUEZ, Carlos Enrique', 'Estrategias de Comunicación y Promoción', NULL),
('PENNANO VILLANUEVA, Carla', 'Fundamentos de Marketing', 'International Marketing, Marketing Estratégico'),
('RIVAS VELARDE,', 'Fundamentos de Marketing', NULL),
('POZO YABAR, Natalia Sofia', 'Gestión Comercial', NULL),
('MEUNIER , Bernard', 'Gestión de Mercados Globales', NULL),
('SAKODA MIZUSHIMA, Diego', 'Gestión de Productos', NULL),
('LADINES AZALIA, Juan Carlos', 'Gestión del Comercio Internacional', 'International Affairs'),
('GARCIA JERI, Oswaldo Carlos', 'Gestión del Comercio Internacional', 'Gestión Internacional de Empresas'),
('ARRIETA PADILLA, Gabriel Lewis', 'Gestión del Comercio Internacional', 'Teoría del Comercio Internacional y Procesos de Integración'),
('PEREZ DE ARMAS, Emilio', 'Gestión Estratégica Comercial, Métricas y Ética', NULL),
('ACOSTA RUIZ, Vanessa Mirtha', 'Gestión Internacional de Empresas', 'Global Branding'),
('MORI CLEMENT, Yadira Isbi', 'Gestión Sostenible de la Oferta Exportable', NULL),
('DEL SOLAR ESCARDO, Diego', 'Global Food & Agribusiness Strategies', NULL),
('VEGA FARRO, Elizabeth', 'Growth Hacking', NULL),
('EDEH , Jude Ndubuisi', 'Innovation, Competitiveness & Export Performance', NULL),
('LIMONGI FRANCA COELHO, Ricardo', 'Intelligent Marketing: Creativity and Innovation in the Age of AI', NULL),
('CALMET GUTIERREZ, Maria Angela', 'Intercultural Competence', NULL),
('VARGAS DE LA JARA, Marisol', 'International Affairs', NULL),
('DIAZ DIAZ, Dagoberto Luis', 'International Business Plan', NULL),
('ALVARADO RUIZ, Paola Alessandra', 'International Business Plan', NULL),
('KALMURAND , Katrin', 'International Human Resources Management', NULL),
('CARRERAS MERINO, Andrea', 'International Human Resources Management', NULL),
('MELLADO SILVA, Maria Antonieta Rosario', 'Investigación de Mercados', NULL),
('TALAVERA SALDARRIAGA, Willy Martin Enrique', 'Investigación de Mercados', NULL),
('ZUÑIGA LAZO, Jenny Lorena', 'Investigación de Mercados', NULL),
('TUTAYA ZEVALLOS, Renan Jesus', 'Investigación de Mercados', 'Marketing Estratégico'),
('GOMEZ ALVIS, ELIZABETH INGRID', 'Investigación de Mercados', NULL),
('MANRIQUE PONCE, Christian Gerardo', 'Marketing B2B', 'Marketing de Contenido, Métricas y Analítica de Marketing'),
('CLAUX FREITAS, Lorena', 'Marketing de Servicios', NULL),
('MAYORGA GUTIERREZ, David Jesus', 'Marketing Estratégico', 'Plan de Marketing'),
('FELICIANO NISHIKAWA, Jose Carlos', 'Marketing Internacional en China y Asia-Pacífico', NULL),
('GONZALES ARBAIZA, Maricruz Del Pilar', 'Marketing Personal para el Mundo Labóral', NULL),
('SCHWALB HELGUERO, Maria Matilde', 'Marketing Sostenible', NULL),
('ROMAN YSEKI, Jorge Hiroshi', 'MVPs and Innovation for Global Markets', NULL),
('MARROU LOAYZA, Julio Estuardo', 'Pensamiento Crítico para Marketing', NULL),
('DE VEGA DE UNCETA, Alejandro', 'Storytelling: Cómo conectar emocionalmente con los consumidores a través de las historias', NULL),
('BRAGAGNINI OLIVER, Rizal Andres', 'Trade Marketing', NULL);

UPDATE professors p
SET 
  especialidad = t.especialidad,
  otros_cursos = t.otros_cursos
FROM temp_prof_updates t
WHERE UPPER(TRIM(p.nombre)) = UPPER(TRIM(t.nombre));
DROP TABLE temp_prof_updates;
