
CREATE TEMP TABLE temp_prof_updates (
  nombre text,
  especialidad text,
  otros_cursos text
);
INSERT INTO temp_prof_updates (nombre, especialidad, otros_cursos) VALUES
('RUIZ PALOMINO, Cesar', 'Evaluación Financiera de las Organizaciones', NULL),
('CASTELLANOS NAVARRETE, Laura Mariela', 'Evaluación Financiera de las Organizaciones', NULL),
('ABREGU NAVEROS, Johana', 'Evaluación Financiera de las Organizaciones', NULL),
('RIVERO PONCE DE LEON, Eduardo Ruben', 'Fundamentos de Contabilidad', NULL),
('CHAVEZ CARDEÑA, Cesar Augusto', 'Fundamentos de Contabilidad', NULL),
('ZELADA ROLLER, Vilma Francisca', 'Fundamentos de Contabilidad', NULL),
('QUIÑONES BOZA, Horacio', 'Fundamentos de Contabilidad', NULL),
('MATSUNO FUCHIGAMI, Ana Cecilia', 'Fundamentos de Contabilidad', 'Principle of Accounting'),
('VELASQUEZ RELAYZE, Jose Luis', 'Gestión de la Información y Métricas de Sostenibilidad Empresarial', NULL),
('BENAVIDES GONZALES, Javier Arturo', 'Inteligencia Artificial Generativa Aplicada a la Información Financiera', 'Valoración Estratégica de Intangibles y Activos del Conocimiento'),
('BAAKLINI , Pascale', 'International Financial Reporting', NULL),
('ZEGARRA BENAVIDES, Carmen Cecilia', 'Normas Contables Internacionales', NULL),
('GARCIA REYES, Karin Maria', 'SAP Hana para la Gestión de la Información', NULL),
('CASTRO ARANA, Javier', 'Tributación Aplicada I', NULL),
('QUISPE CHUMPE, Emerzon', 'Tributación Aplicada II', NULL),
('LLONTOP MEJIA, Miguel Angel', 'Agentes Inteligentes', 'Gestión de Proyectos'),
('ROJAS VILLANUEVA, Uwe', 'Algoritmos y Estructura de Datos', 'Herramientas de Programacion con Python, Principios de Machine Learning, Técnicas Avanzadas para el Análisis de Datos'),
('FABIAN ARTEAGA, Junior John', 'Analítica de la Web', 'Deep Learning, Ingeniería de Datos, SQL para la Toma de Decisiones'),
('TOVAR GALARRETA, Juan Carlos', 'Big Data Analytics', 'Computación de Alto Desempeño y Cloud Computing'),
('AMADO GARFIAS, Alonso', 'Business Analytics', 'Infraestructura Tecnológica, Machine Learning'),
('WAM BALTODANO, Javier Guillermo', 'Business Intelligence', NULL),
('AGUIRRE RUIZ, Jose Jonathan', 'Ciberseguridad', NULL),
('ESPEZUA LLERENA, Soledad', 'Data Mining', 'Nivelación en Informática'),
('VALERA GARCIA, Paulo Enrique', 'Desarrollo de Soluciones Empresariales', 'Infraestructura Tecnológica, Ingeniería de Datos'),
('HUAMAN LINARES, Jose', 'Desarrollo de Soluciones Empresariales', NULL),
('WONG POGGI, Jennifer Karina', 'Design Thinking and Technological Innovation', 'Metodologías Ágiles'),
('HIUMETTRI BLANCO, Victor Kervin', 'Design Thinking and Technological Innovation', 'Emprendimiento Tecnológico, Innovación, Tecnologías y Emprendimiento: El caso de Silicon Valley, Metodologías Ágiles, Marketing Digital y Redes Sociales'),
('RAMIREZ VINATEA, Jimena', 'Design Thinking and Technological Innovation', NULL),
('MARTINEZ QUIÑE, Lourdes', 'Design Thinking and Technological Innovation', NULL),
('FANG CHONG, Sergio Enrique', 'Emprendimiento Tecnológico', 'Trabajo Final de Ingeniería Empresarial'),
('LAZARTE AGUIRRE, Luz Andrea', 'Emprendimiento Tecnológico', NULL),
('DIAZ DOMINGUEZ, Carlos Manuel', 'Excel Avanzado para la Gestión Empresarial', 'Nivelación en Informática'),
('STUCCHI PORTOCARRERO, Luciano', 'Física', NULL),
('CARBAJAL VIGO, Saneli Alcides', 'Física', 'Introducción a la Cosmología y la Ciencia de la Vida, Pensamiento Sistémico'),
('QUIROZ GONZALEZ, Jorge Luis Martín', 'Física', NULL),
('LAZO LAZO, Juan Guillermo', 'Formulación y Evaluación de Proyectos', 'Investigación de Operaciones'),
('GONZALEZ PALOMINO, JORGE MARTIN', 'Formulación y Evaluación de Proyectos', NULL),
('MAEHARA ALIAGA DE BENITES, Rocio Paola', 'Fundamentos de Analítica', NULL),
('CUMPA OBREGON, Nelson Enrique', 'Gerencia de Ingeniería de Valor', 'Inteligencia Artificial Aplicada a la Cadena de Suministros, Procesos de Distribución, Procesos de Producción'),
('STUART ALVARADO, Maria Gabriela', 'Gerencia de Ingeniería de Valor', NULL),
('PALOMINO GARCIA, Jorge Ciro', 'Gestión de Proyectos', NULL),
('AYMA QUIRITA, Victor Hugo', 'Herramientas de Programación', NULL),
('MUÑOZ CASILDO, Nehil Indalicio', 'Herramientas de Programación', 'Ingeniería de Datos'),
('QUISPE AYALA, Martha Roxana', 'Herramientas de Programación', 'Nivelación en Informática'),
('SIERRA FLORES, Luis Miguel', 'Herramientas de Programación', 'Investigación de Operaciones'),
('CARRILLO THORNE, Juan Diego', 'Historia Crítica del Diseño', NULL),
('SICCHA AYVAR, Hobber Aristides', 'Infraestructura Tecnológica', NULL),
('GARMENDIA FOSSA, Francisco Antonio', 'Ingeniería de Procesos', 'Procesos de Suministros, Trabajo Final de Ingeniería Empresarial, Gestión Internacional de Empresas'),
('CHICHIZOLA PORRAS, Victor Augusto', 'Ingeniería de Procesos', NULL),
('TALAVERA LOPEZ, Alvaro Gustavo', 'Inteligencia Computacional', 'Trabajo Final de Ingeniería de la Información I'),
('RODRIGUEZ SATIZABAL, Simon Andres', 'Introducción a la Cosmología y la Ciencia de la Vida', NULL),
('PELAYO BALDARRAGO, Mara Elizabeth', 'Introducción a la Cosmología y la Ciencia de la Vida', NULL),
('CHONG CHONG, Mario Gustavo', 'Introducción a la Ingeniería', 'Procesos de Distribución'),
('ORTIZ VALENCIA, Alejandro Leopoldo', 'Introducción a la Ingeniería', 'Metodologías Ágiles, Transformación Digital y Gestión del Cambio'),
('MACHUCA DE PINA, Juan Manuel', 'Investigación de Operaciones', 'Matemáticas Discretas para la Computación'),
('LIBAQUE SAENZ, Christian Fernando', 'Métodos de Investigación Cuantitativa', NULL),
('BRAVO ORELLANA, Edgardo Ricardo', 'Métodos de Investigación Cuantitativa', NULL),
('SENMACHE SARMIENTO, Jose Manuel Martin', 'Nivelación en Informática', NULL),
('ZALDIVAR PEÑA, Doris Adriana', 'Nivelación en Informática', NULL),
('TORRES SUAREZ, Rolando Martin', 'Nivelación en Informática', NULL),
('PÉREZ - GODOY BALLÓN, Luis Alberto', 'Pensamiento Sistémico', NULL),
('SALCEDO MANSILLA, Jorge Manuel', 'Procesos de Producción', NULL),
('RIVERO CESPEDES, Luis Felipe', 'Procesos de Producción', NULL),
('CORNEJO RIVERO, Alvaro Alexander', 'Prototipea tu Idea con Impresión 3D', NULL),
('SZOSTEK , Agnieszka', 'Sem. Defining Powerful Experience Strategy', NULL),
('JURBURG MELNIK, Daniel Andres', 'Sem. Defining Powerful Experience Strategy', NULL),
('FLORCZAK , Waldemar Han', 'Sem. Introduction to Operational Research', NULL),
('LUNA , Ana Eugenia', 'Tecnología para el Desarrollo Sostenible', NULL),
('SOTOMAYOR CABRERA, Aristides', 'Tecnología para el Desarrollo Sostenible', NULL),
('RODRIGUEZ SERRA, Michelle', 'Tecnología y Negocios Digitales', NULL),
('DROGUETT QUEZADA, Nicolas Patricio', 'Tecnología y Negocios Digitales', NULL),
('HAAKER MASSA, Aisa', 'Tecnología y Negocios Digitales', NULL),
('ALIAGA ALIAGA, Walter', 'Trabajo Final de Ingeniería Empresarial', NULL),
('RETAMOZO ESCOBAR, Jaliya', 'Acto Jurídico', 'Responsabilidad Extracontractual'),
('CHAVEZ VERASTEGUI, Christian', 'Acto Jurídico', NULL),
('PIEROLA CASTRO, Noe Fernando Nicolas', 'AI Regulation: A Global and Comparative Perspective', NULL),
('ZUÑIGA PALOMINO, Mario Augusto', 'Análisis Económico del Derecho', NULL),
('ESPEJO DONAIRE, Andrea Patricia', 'Arbitraje', NULL),
('TOVAR GIL, Maria Del Carmen Violeta', 'Arbitraje', NULL),
('FERRERO DIAZ, Javier Ignacio', 'Arbitraje', NULL),
('HUANCO PISCOCHE,', 'Arbitraje', NULL),
('HUANCO PISCOCHE, Henry Wilder', 'Contratos', 'Derechos Reales'),
('MADRID HORNA, Victor', 'Contratos', 'Obligaciones'),
('SORIA AGUILAR, Alfredo Fernando', 'Contratos Especiales', NULL),
('GABRIEL RIVERA, Jose Luis', 'Contratos Especiales', 'Economía y Derecho'),
('VASQUEZ REBAZA,', 'Contratos Especiales', NULL),
('NUÑOVERO CISNEROS, Lucia Betty', 'Criminología y Derecho Penitenciario', NULL),
('PEREZ', 'Criminología y Derecho Penitenciario', NULL),
('TIRADO BARRERA, Jose Antonio', 'Derecho Administrativo I', NULL),
('GOMEZ APAC, Hugo Ramiro', 'Derecho Administrativo I', NULL),
('MORI TORRES, Natalia Vanessa', 'Derecho Administrativo II', NULL),
('FARFAN SOUSA, Ronnie Ado', 'Derecho Administrativo II', 'Sem. de Derecho Administrativo y Regulación'),
('ARMESTAR BRUNO, Gloria Maria', 'Derecho Civil y Comercial', NULL),
('RAMIREZ OTERO, Lorena Cecilia', 'Derecho Civil y Comercial', 'Sociedades'),
('PARODI LUNA, Maria Beatriz', 'Derecho Civil y Comercial', NULL),
('FERRANTE , Alfredo', 'Sem. Derecho Comparado: Aspectos Prácticos y Metodológicos', NULL),
('LIZARRAGA VERA-PORTOCARRERO, Anthony', 'Derecho Concursal', NULL),
('ALBAN GONZALEZ, Javier Ignacio', 'Derecho Constitucional General', 'Derecho Procesal Constitucional'),
('NEYRA ZEGARRA, Ana Cristina', 'Derecho Constitucional General', NULL),
('PLACIDO VILCACHAGUA, Alex Fernando', 'Derecho de Familia y Sucesiones', NULL),
('MARES RUIZ, Carla Elena', 'Derecho de la Empresa', 'Derecho Tributario I'),
('RUIZ COLMENARES,', 'Derecho de la Empresa', NULL),
('VASSALLO BURNEO, Nicolas', 'Derecho Internacional Privado', NULL),
('ZELADA ACUÑA, Carlos Joel', 'Derecho Internacional Público', NULL),
('PRELLE MAYURI, Herbert Victor Ricardo', 'Derecho Laboral I', NULL),
('TOYAMA MIYAGUSUKU, Jorge Luis', 'Derecho Laboral I', NULL),
('CASTILLO FUENTES, Diego Sebastian', 'Derecho Laboral I', NULL),
('LORA ALVAREZ, German Lino', 'Derecho Laboral I', 'Derecho Laboral y Tributario'),
('CASTRO POSADAS, Eric Christian', 'Derecho Laboral II', NULL),
('GILDEMEISTER RUIZ HUIDOBRO, Alfredo', 'Derecho Laboral y Tributario', NULL),
('SALAZAR TIRADO,', 'Derecho Laboral y Tributario', NULL),
('GARCIA BELAUNDE SALDIAS, Diego', 'Derecho para los Negocios Internacionales', 'Negociaciones Comerciales Internacionales'),
('CARO JOHN, Jose Antonio', 'Derecho Penal', NULL),
('REAÑO PESCHIERA, José', 'Derecho Penal', NULL),
('BENDEZU BARNUEVO, Rocci Fiorella', 'Derecho Penal', 'Derecho Penal Económico'),
('CUBA COPELLO, YVO CAMILO', 'Derecho Procesal Civil', NULL),
('RIVAS CASO, Gino Elvio', 'Derecho Procesal Civil', NULL),
('CAMPOS BERNAL, Heber Joel', 'Derecho Procesal Constitucional', NULL),
('CAYO RIVERA SCHREIBER, Maria Jimena Soledad /', 'Derecho Procesal Penal', NULL),
('DIAZ TENORIO, Diego Arturo', 'Derecho Tributario I', NULL),
('HUERTAS LIZARZABURU, Martha Cristina', 'Derecho Tributario I', NULL),
('POLO CHIROQUE, ROBERTO EDWARD', 'Derecho Tributario II', NULL),
('RUIZ COLMENARES, Melissa Sarahi', 'Derecho Tributario II', NULL),
('RAVINA SANCHEZ, Raul Fernando', 'Derechos Reales', NULL),
('GINES CASTELLET, Nuria', 'Derechos Reales y Contratos: Teoría Clásica y Transformaciones Contemporáneas', NULL),
('ALONSO HERRERA, Jorge Ivan', 'Destrezas Legales y Económicas para Litigar en Libre Competencia', NULL),
('ZUÑIGA PALOMINO,', 'Destrezas Legales y Económicas para Litigar en Libre Competencia', NULL),
('URBINA LOVON, Erick Edwin', 'Economía y Derecho', NULL),
('IPARRAGUIRRE ROMERO, Gianfranco', 'Economía y Derecho', NULL),
('LEON LUNA,', 'Economía y Derecho', NULL),
('COGORNO FALCONE, Sandro Agustin', 'Fusiones y Adquisiciones', NULL),
('CORTINA MENDOZA, Roxana Marina', 'Inglés Jurídico', NULL),
('BARDALES MENDOZA, Enrique Rosendo', 'Instituciones de Derecho Mercantil', NULL),
('ZUÑIGA SCHRODER, Humberto Angel', 'Introducción al Derecho', NULL),
('OLIVOS CELIS, Milagros Katherine', 'Introducción al Derecho', 'Personas del Derecho Civil'),
('TALAVERA CANO, Andres Alvaro', 'Introducción al Derecho', NULL),
('VASQUEZ REBAZA, Walter Humberto', 'Obligaciones', NULL),
('BRAVO ARANA, Grismi Claudia', 'Organizaciones Internacionales', NULL),
('CLAROS ABARCA, Roberto Fernando', 'Organizaciones Internacionales', NULL),
('NEIRA LUCAR, Melissa Judith', 'Personas del Derecho Civil', NULL),
('ALIAGA FARFAN, Jeanette Sofia', 'Regulación Bancaria y Mercado de Capitales', NULL),
('ABAD YUPANQUI, Samuel Bernardo', 'Sem. de Derecho Constitucional', NULL),
('FREITAS CABANILLAS, Rodrigo Andrés', 'Técnicas de Persuasión y Moot Court', NULL),
('HUANCO', 'Técnicas de Persuasión y Moot Court', NULL),
('REAÑO PESCHIERA, José Leandro', 'Tendencias Jurisprudenciales del Derecho Penal Económico', NULL),
('SIMONS PINO, Adrian Marcius', 'Teoría General del Proceso', NULL),
('CHIRINOS VIDAURRAZAGA, Gonzalo Guillermo', 'Teoría General del Proceso', NULL),
('MALPARTIDA TABUCHI, Daniel Humberto', 'Análisis Financiero', NULL),
('LUNA VICTORIA CONTRERAS, Rolando Alfonso', 'Análisis y Gestión de Riesgos', NULL),
('RAUNELLI MONTERO, Jose Carlos', 'Análisis y Gestión de Riesgos', 'Finanzas Cuantitativas, Fundamentos de Finanzas');

UPDATE professors p
SET 
  especialidad = t.especialidad,
  otros_cursos = t.otros_cursos
FROM temp_prof_updates t
WHERE UPPER(TRIM(p.nombre)) = UPPER(TRIM(t.nombre));
DROP TABLE temp_prof_updates;
