
CREATE TEMP TABLE temp_prof_updates (
  nombre text,
  especialidad text,
  otros_cursos text
);
INSERT INTO temp_prof_updates (nombre, especialidad, otros_cursos) VALUES
('RHO , Haedong', 'Microeconomía I', NULL),
('CHAVEZ COTRADO, Jorge Francisco', 'Microeconomía I', 'Microeconomía II'),
('PORRAS MENDOZA, Linda Janet', 'Microeconomía I', 'Sem. Economía y Gestión de Programas Sociales'),
('BONIFAZ FERNANDEZ, Jose Luis', 'Microeconomía II', 'Organización Industrial'),
('CERNADES GOMEZ, Jesus', 'Nivelación en Matemáticas', NULL),
('VENEGAS PALACIOS, Edgard Kenny', 'Nivelación en Matemáticas', NULL),
('GONZALEZ IZQUIERDO, Jorge Domingo', 'Política Económica', NULL),
('ARMAS RIVAS, Adrian Alejandro', 'Política Económica', NULL),
('ARON SAID, Ana Sofia', 'Sem. de la Estrategia a la Implementación de Políticas Públicas', NULL),
('DIAZ GAMARRA, Jose Guillermo', 'Sem.Tópicos en Organización Industrial', NULL),
('ARAOZ FERNANDEZ, Mercedes Rosalba', 'Teoría del Comercio Internacional', NULL),
('ZEVALLOS URQUIETA, Hector Augusto', 'Teoría del Comercio Internacional', NULL),
('CANTA TERREROS, Michel Rodolfo', 'Teoría del Desarrollo Económico', NULL),
('MALDONADO ZAMBRANO, Stanislao Humberto', 'Tópicos de Evaluación de Impacto', NULL),
('BENITES SANCHEZ, Luis Enrique', 'Análisis Multivariado para los Negocios', 'Analítica de Datos para los Negocios'),
('DONGO ROMAN, Andie Bryan', 'Análisis Multivariado para los Negocios', NULL),
('GARCIA CESPEDES, Carlos Jeffer', 'Análisis Multivariado para los Negocios', NULL),
('PORRAS CERRON, Jaime Carlos', 'Análisis Multivariado para los Negocios', 'Fundamentos de Analítica'),
('CASTILLO ISISOLA, Frank Josue', 'Análisis Multivariado para los Negocios', NULL),
('VASQUEZ ORE, Marco Antonio', 'Analítica de Datos para los Negocios', 'Macros en Excel para No Programadores, Nivelación en Informática'),
('MAEHARA ALIAGA, Yoshitomi Eduardo', 'Analítica de Datos para los Negocios', 'Herramientas de Programación'),
('BUSTAMANTE BAUTISTA, Beatriz Esther', 'Analítica de Datos para los Negocios', 'Nivelación en Informática'),
('RAMOS PERALTA, Karim Mabel', 'Analítica de Datos para los Negocios', 'Nivelación en Informática'),
('REATEGUI SCHWARZ, Gerardo', 'Asset-Light Business Models', NULL),
('VILLACORTA HOLGUIN, Katherine Lilia', 'Business Agility', 'Design Thinking and Technological Innovation'),
('PERALTA MANSILLA, Norma Gisela', 'Business Agility', 'Emprendimiento e Innovación, Proyección Social'),
('FLORES CASTRO, Juan Alejandro', 'Creación de Valor y Toma de Decisiones', 'Diseño Organizacional y Estrategia, Gestión de la Innovación'),
('Díaz Rojas, Carlos Andres', 'Creación de Valor y Toma de Decisiones', 'Métodos Cuantitativos para la Gestión en las Organizaciones, Sistemas de Información y Análisis de Datos'),
('LAFOSSE QUINTANA, Wilfredo Jesus', 'Creación de Valor y Toma de Decisiones', 'Dirección Estratégica'),
('PAIVA ZARZAR, Roberto Alcides', 'Dirección Estratégica', NULL),
('PALACIOS MATOS, Maria Del Pilar Amelia', 'Dirección Estratégica', 'Gestion del Capital Humano, Liderazgo, Transformación Digital y Gestión del Cambio'),
('UEYONAHARA MATZUMOTO, Jorge Antonio', 'Diseño de Negocios Circulares y Desafío Climático', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas, Liderazgo, Sostenibilidad Empresarial y Modelos de Negocios Circulares'),
('REBAZA CARO, Nancy', 'Diseño Organizacional y Estrategia', 'Fundamentos de las Ciencias Empresariales, Gestión del Cambio y Transformación Cultural, Liderazgo'),
('ACUÑA SILLO, Elba Lourdes', 'Diseño Organizacional y Estrategia', 'Estrategia, Fundamentos de las Ciencias Empresariales'),
('JAYME MOSQUERA, Guadalupe Desiree', 'Diseño Organizacional y Estrategia', 'Fundamentos de las Ciencias Empresariales, Gestión de Personas, Gestión del Cambio y Transformación Cultural'),
('BUTRON PIPOLI, Giuliana Maria', 'Diseño Organizacional y Estrategia', NULL),
('GRANTHON URIARTE, Ronald Jefrie', 'Diseño Organizacional y Estrategia', 'Fundamentos de las Ciencias Empresariales, Liderazgo'),
('TRUJILLO SOSA, Jorge Enrique', 'Emprendimiento e Innovación', 'Fundamentos de las Ciencias Empresariales, Proyecto Empresarial'),
('SANCHEZ JUGO, Isabel', 'Emprendimiento e Innovación', 'Fundamentos de las Ciencias Empresariales, Comportamiento del Consumidor'),
('VILLANUEVA PEREZ, Humberto Jesus', 'Emprendimiento e Innovación', NULL),
('VILLEGAS VALLADARES, Shirley Rubi', 'Emprendimiento e Innovación', 'Proyecto Empresarial'),
('BELTRÁN PUERTA, Jorge', 'Emprendimiento e Innovación', NULL),
('RIVAS VELARDE, Andrea Carolina', 'Emprendimiento e Innovación', 'Marketing Estratégico'),
('RODRIGUEZ CORNEJO, Juan Carlos', 'Formación y Desarrollo del Talento', NULL),
('CORNEJO ALVAREZ DE ESQUIVES, Ana Lourdes', 'Fundamentos de las Ciencias Empresariales', 'Proyecto Empresarial'),
('WEINBERGER VILLARAN, Karen Edith', 'Fundamentos de las Ciencias Empresariales', NULL),
('DEL CASTILLO MORY, Elsa Catalina', 'Fundamentos de las Ciencias Empresariales', NULL),
('MANOSALVA MENDOZA, Maritza Elva Juana', 'Fundamentos de las Ciencias Empresariales', 'Gestión del Cambio y Transformación Cultural'),
('MEDINA WONG, Gwendolyne', 'Fundamentos de las Ciencias Empresariales', NULL),
('ANTICONA SUAREZ, Erick Olson', 'Gestión de la Cadena de Suministros', 'Gestión de Operaciones en las Organizaciones, Proyecto Empresarial, Logística Internacional, Tecnologías Aplicadas a la Distribución Física Internacional'),
('OLIVEIRA CAMBIASO, Daniel Alessandro', 'Gestión de la Cadena de Suministros', NULL),
('CHICHIZOLA FAJARDO, Cristina Elizabeth', 'Gestión de la Cadena de Suministros', 'Gestión de Operaciones en las Organizaciones, Métodos Cuantitativos para la Gestión en las Organizaciones'),
('PECASTAING , Nicolas', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas', NULL),
('PRIALE VALLE, Maria Angela', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas', NULL),
('TEJADA MATOS, Susana Rocío', 'Gestión de la Sostenibilidad Social y Ambiental en las Empresas', NULL),
('SARAVIA VERGARA, Enrique Andres', 'Gestión de Operaciones en las Organizaciones', 'Métodos Cuantitativos para la Gestión en las Organizaciones'),
('LARIOS FRANCIA, Rosa Patricia', 'Gestión de Operaciones en las Organizaciones', 'Gestión y Emprendimiento en la Industria Musical, Investigación Aplicada a los Negocios'),
('ESQUIVES GUERRA, Marcial Ruben', 'Gestión de Personas', 'Gestión del Cambio y Transformación Cultural, Liderazgo, Selección y Evaluación de Personal'),
('FUCHS ANGELES, Rosa Maria', 'Gestión de Personas', NULL),
('OTINIANO CARBONELL, Martin Carlos', 'Gestión de Personas', 'Gestión del Cambio y Transformación Cultural'),
('CAMPOS FERNANDEZ, Luis Enrique', 'Gestión de Riesgos según el PMI', NULL),
('BRAVO MONTEVERDE, Guido Humberto', 'Gestión del Cambio y Transformación Cultural', 'Liderazgo'),
('ESCRIBENS OLAECHEA, Mario Eduardo', 'Gestion del Capital Humano', 'Introducción a la Ingeniería, Tecnología y Negocios Digitales'),
('GOMEZ CHANGA, Sarita Julia', 'Gestión Estratégica de Organizaciones Deportivas', 'Liderazgo, Marketing Deportivo'),
('MOSCOSO ZAMBRANO, Renzo Mauricio', 'Gestión Estratégica de Organizaciones Deportivas', 'Marketing Deportivo'),
('Alpaca', 'Gestión y Emprendimiento en la Industria Musical', NULL),
('CHAVEZ CARRUITERO, Jimmy Rosendo', 'Innovación y Gestión en Negocios Digitales', 'Sistemas de Información y Análisis de Datos'),
('LINARES TORRES, Freddy', 'Innovación y Gestión en Negocios Digitales', 'Digital Product Design & Metrics, Neuromarketing'),
('GARCIA FRY, Andrea', 'Innovación y Gestión en Negocios Digitales', NULL),
('ESPINEL HUERTAS DEL PINO, Maria Pia', 'Innovación y Gestión en Negocios Digitales', NULL),
('CANO LANZA, Ana Maria', 'Investigación Aplicada a los Negocios', NULL),
('CHAVES CUZZI, Daniela Maria', 'Liderazgo', NULL),
('HERAUD GOICOCHEA, Sylvia', 'Liderazgo', NULL),
('Vivanco Loomer, Luis Miguel', 'Liderazgo', NULL),
('Vargas Soto, Veronica', 'Liderazgo', NULL),
('CASTRO SEGURA, Barbara', 'Liderazgo', NULL),
('SALVADOR , Elisa', 'Managing Innovation and Creativity - Negotiation for International Managers', NULL),
('DAVALOS CHACON, Jorge Elias', 'Métodos Cuantitativos para la Gestión en las Organizaciones', NULL),
('BRESCIANI CHAVEZ, Fernando Manuel', 'Métodos Cuantitativos para la Gestión en las Organizaciones', 'Fundamentos de Finanzas'),
('GALVEZ PAIBA, Blanca Eliana', 'Proyecto Empresarial', NULL),
('ARANDA IPINCE, Duilio Angel', 'Sistemas de Información y Análisis de Datos', 'Arquitectura del Sistema de Información, Nivelación en Informática, Power BI: Transforma y Visualiza Datos para Decisiones Informadas'),
('INFANTE CHAVEZ, Jorge Ricardo', 'Sistemas de Información y Análisis de Datos', 'Arquitectura del Sistema de Información, Excel Avanzado para la Gestión Empresarial, Nivelación en Informática'),
('CASAFRANCA ROSAS, Juan Carlos', 'Toma de Decisiones - Simulador: Blue Ocean Strategy', NULL),
('VALDIVIA CORRALES, Gustavo', 'Antropología', 'Antropología Económica'),
('CASTELLANOS DEL PORTAL, Themis Aidee', 'Antropología', NULL),
('Hidalgo Bonicelli, Alejandra Lucia', 'Antropología', 'Investigación Académica'),
('PAGAN SANCHEZ, Antonio Jose', 'China Contemporánea: Sociedad, Política y Relaciones Internacionales', 'Relaciones Internacionales'),
('PASTOR TORRES, Gustavo Ricardo', 'Ciencia Política', 'Investigación Académica, Pensamiento Social Contemporáneo'),
('VERGARA PANIAGUA, Alberto', 'Ciencia Política', NULL),
('BLYDAL , Carl Johan', 'Ciencia Política', NULL),
('LANEGRA QUISPE, Ivan Kriss', 'Ciencia Política', NULL),
('MARIUS VASQUEZ, Paola', 'Ciencia Política', NULL),
('ENCINAS ZEVALLOS, Daniel', 'Ciencia Política', 'Política Comparada'),
('AVALOS BARRIO DE MENDOZA, Vicente Daniel', 'Ciencia Política', 'Pensamiento Social Contemporáneo'),
('GODOY MEJIA, Jose Alejandro', 'Ciencia Política', 'Investigación Académica'),
('NOLES COTITO, Mariela Ines', 'Ciencia Política', NULL),
('BARRENECHEA CARPIO, Rodrigo', 'Ciudadanía y Democratización', 'Poder e Instituciones'),
('CHENG MATSUNO, Vanessa Cecilia', 'Contemporary Public Administration Seminar', NULL),
('TACUCHE MORENO, Luis Enrique', 'Discriminación y Políticas Públicas', NULL),
('SANBORN , Cynthia Ann', 'Economía Politica Internacional', NULL),
('FLORES NORIEGA DE BENITES, Eva Paulina', 'Investigación Académica', NULL),
('DEBENEDETTI LUJAN, Bruno Edoardo', 'Investigación Académica', 'Destrezas Legales I, Sem. de Tesis'),
('GIESECKE CHERO, Micaela', 'Investigación Académica', NULL),
('CASTILLO THORNE, Krishna David', 'Investigación Académica', 'Sociología'),
('DEL MASTRO VECCHIONE, Marco Hugo', 'Investigación Académica', 'Pensamiento Social Contemporáneo'),
('SETLAK , Magdalena Anna', 'Investigación Académica', NULL),
('GUTIERREZ COTTLE, Maria Cristina', 'Investigación Académica', NULL),
('VALLEJO RIVERA, Elizabeth Rocio', 'Investigación Académica', NULL),
('GORENSTEIN RIVERA, SHARON', 'Investigación Académica', NULL),
('PIZARRO BAUMANN, Maria Jimena', 'Investigación Académica', NULL),
('STIGLICH VARGAS, Maria Elizabeth', 'Investigación Académica', 'Sicología'),
('CRUZADO SILVERII, Miguel Gabriel', 'Pensamiento Social Contemporáneo', NULL),
('KOGAN COGAN, Liuba', 'Pensamiento Social Contemporáneo', NULL),
('PROTZEL DE AMAT, Jaime Javier', 'Pensamiento Social Contemporáneo', NULL),
('PEREZ RECALDE , Guadalupe', 'Pensamiento Social Contemporáneo', 'Procesos sociopolíticos de América Latina a través del Cine, Sociología'),
('MARIANI , Santiago', 'Procesos sociopolíticos de América Latina a través del Cine', NULL),
('PEÑA ANAYA, Maria Luisa', 'Proyección Social', NULL),
('VARELA GARCIA, Cinthia Patricia Alexandra', 'Proyección Social', NULL),
('VIDAL IZAGUIRRE, Patricia Estela', 'Proyección Social', NULL),
('ZUÑIGA BRAVO, Martha Eliana', 'Proyección Social', NULL),
('FLORES GUZMAN, ROSIO MILAGRO', 'Proyección Social', NULL),
('BAMBAREN LUKIS, Fernando Armando', 'Relaciones Internacionales', NULL),
('MENESES GONZALES, Gonzalo Alfredo', 'Sicología', NULL),
('RODRIGUEZ CUADROS DE MURO, Lorena', 'Sicología', NULL),
('YOSHIDA GOTO, Erika', 'Sicología', NULL),
('OTINIANO CAMPOS, Fiorella', 'Sicología', NULL),
('SOLANO SILVA, Dante Junior', 'Sicología', NULL),
('BIELICH SALAZAR, Claudia Teresa', 'Sociología', NULL),
('COBIAN OVALLE DE PLAZA, Maria Beatriz', 'Sociología', NULL),
('MEDRANO GARCIA, Fabricio Manuel', 'Aspectos Jurídicos para los Negocios', 'Derecho Laboral y Tributario'),
('PANTIGOSO VELLOSO DA SILVEIRA, Francisco', 'Aspectos Tributarios para la Empresa', 'Derecho Laboral y Tributario'),
('DE LA TORRE ONOFRE, Christian Raul', 'Auditoría', NULL),
('SOTO MUJICA, José Carlos Humberto', 'Constitución y Formalización de MYPES', 'Fundamentos de Contabilidad'),
('ALVA GONZALES, Edgar Paul', 'Contabilidad de Costos', 'Contabilidad de Gestión'),
('YAÑEZ QUIROZ, Mario Alberto', 'Contabilidad Financiera Aplicada', 'Fundamentos de Contabilidad'),
('JARA MIRANDA, Renan Geoffrey', 'Contabilidad Financiera Intermedia', NULL),
('CHONG LEON, Esteban', 'Contabilidad Financiera Intermedia', NULL),
('QUEVEDO ALEJOS, Maria Isabel Alejandra', 'Contabilidad Financiera Intermedia', NULL),
('ASTORGA DE LA CRUZ, Brandelt Jesús', 'Contabilidad Financiera Intermedia', 'Investigación para Contadores'),
('MARADIEGUE , SANTIAGO ALBERTO', 'Contabilidad Financiera Intermedia', NULL),
('ROSAS AMBROSIO, Annel Victoria', 'Contabilidad Financiera Intermedia', NULL),
('ARIAS PICON, Norma Beatriz', 'Contabilidad Financiera Intermedia', 'Fundamentos de Contabilidad, Management Accounting'),
('CACERES LOAYZA, Rosa Graciela', 'Contabilidad Financiera Intermedia', 'Fundamentos de Contabilidad'),
('RUIZ HURTADO, Pedro Cesar', 'Contabilidad Financiera Intermedia', 'Evaluación Financiera de las Organizaciones, Evaluación Financiera para No Contadores'),
('ESCOBAR ESPINO, Roberto Diego', 'Contabilidad para la Toma de Decisiones', 'Fundamentos de Contabilidad'),
('SILVA TORRALVA, Hans Jhordan', 'Contabilidad para la Toma de Decisiones', 'Fundamentos de Contabilidad, Gestión y Costos Estratégicos'),
('MATEO UNCHUPAICO, Maria Victoria', 'Contabilidad para la Toma de Decisiones', NULL),
('LOMBARDI VALLE, GINA ANGELA', 'Contabilidad para la Toma de Decisiones', NULL),
('ONTON LOPEZ, Renzo Jesus', 'Contabilidad y Finanzas Avanzadas', NULL),
('RUIZ LLACSAHUANGA, Ketty Margarita', 'Control Interno y Gestión de Riesgo', NULL);

UPDATE professors p
SET 
  especialidad = t.especialidad,
  otros_cursos = t.otros_cursos
FROM temp_prof_updates t
WHERE UPPER(TRIM(p.nombre)) = UPPER(TRIM(t.nombre));
DROP TABLE temp_prof_updates;
