name = "campuslink-api"
main = "src/index.ts"
compatibility_date = "2026-08-27"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
ALLOWED_ORIGIN = "https://cajaazul.pages.dev"
SUPABASE_URL = "https://mevfhlhwrrkbhppgeyaj.supabase.co"
WEBHOOK_URL_BASE = "https://campuslink-api.cajaupazul.workers.dev"
CONVERTER_API_URL = "https://campuslink-converter.onrender.com"

[[r2_buckets]]
binding = "COURSE_MATERIALS"
bucket_name = "course-materials"

[[r2_buckets]]
binding = "COURSE_IMAGES"
bucket_name = "course-images"

[[r2_buckets]]
binding = "PROFILE_AVATARS"
bucket_name = "profile-avatars"

[[r2_buckets]]
binding = "PROFILE_FRAMES"
bucket_name = "profile-frames"

[[r2_buckets]]
binding = "GRUPOS"
bucket_name = "grupos"

[[r2_buckets]]
binding = "THUMBNAILS"
bucket_name = "thumbnails"

[[r2_buckets]]
binding = "ANNOUNCEMENTS"
bucket_name = "announcements"

[[r2_buckets]]
binding = "LIBRARY"
bucket_name = "library"

[[r2_buckets]]
binding = "BLACKBOARD_DOWNLOADS"
bucket_name = "blackboard-downloads"
